### ISSUE TITLE
Функция загрузки модуля через Web UI

### ISSUE THREAD

**Issue by alexeyzimarev** [Z-Wave-Me/home-automation#148]
Нужна функция загрузки модулей через веб-интерфейс. Сейчас для того, чтобы разместить новый модуль, надо использовать sftp. Представим, что появятся сторонние разработчики модулей, пользователи захотят их ставить, а user-friendly способа сделать это нет. На Vera такая возможность существует.

**Comment by PoltoS** [comment]
теперь есть developer.z-wave.me

**Comment by alexeyzimarev** [comment]
Супер
