### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by johanpoirier** [Z-Wave-Me/home-automation#194]
Hi,

I updated ma razberry with the version 2.0.1-rc7 and I have encoding issues now.
All temperature in Celisus °C are displayed as �C and all the labels with accents have � instead.

Is UTF-8 set everywhere ?

Thanks.

**Comment by PoltoS** [comment]
Fixed in Z-Way code

**Comment by johanpoirier** [comment]
Thanks.

**Comment by johanpoirier** [comment]
I just installed rc10 and Celsius temperatures are still displayed as �C.
