### ISSUE TITLE
ThermostatDevice module

### ISSUE THREAD

**Issue by kozlowski-mathias** [Z-Wave-Me/home-automation#196]
In ThermostatDevice module.json line 62, optionLabels should be "namespaces:devices_sensorMultilevel:deviceName" and not switchBinary...

**Comment by aivs** [comment]
thanks, fixed

**Comment by kozlowski-mathias** [comment]
Not so quick! ;)
Change also vDev for vDevSwitch at .performCommand("on"/"off") in checkTemp function otherwise nothing is switching! :-p
And still, there is a NaN bug somewhere in thermostat widget display because of an invalid "metrics:level" reading...

**Comment by aivs** [comment]
fixed vDevSwitch.performCommand(this.config.heaton ? "on" : "off");
For me thermostat work well
We will fix a bug with NaN at next time

**Comment by kozlowski-mathias** [comment]
Sorry for that but I'm always on ThermostatDevice code... but now with working node-inspector!
In my case, switch is never toggled when temp sensor signals a positive change. Now with debugger I can tell why: EventEmitter does not rebuild correctly "this" context: no vDev property and undefined this.config.switch and this.config.sensor values. Event is handled but (vDevSwitch && vDevSensor && vDev) is always false...

**Comment by PoltoS** [comment]
this is strange as this should refer to the object placed before "." in self.checkTemp and this.checkTemp.

Both refers to module object and this code worked for us.

I don't really understanf why is EventEmitter is metioned in your comment, since this hander is never called via EvenEmitter.

**Comment by kozlowski-mathias** [comment]
I've placed a breakpoint within the checkTemp function and I see the function is called by EventEmitter from the callstack when my sensor is sending a temp value change...

**Comment by PoltoS** [comment]
Indeed...

Fixed: https://github.com/Z-Wave-Me/home-automation/commit/93fa97081c673ecd2756a5ecad722d0c2fbcd33f.

Please try this fix

**Comment by PoltoS** [comment]
Excuse, fixed again. this: f600069913338d96319d4e57a09902e882b0e0a4

**Comment by kozlowski-mathias** [comment]
Yes, of course, I've saw the typo ;) fixed it by myself and currently reinstalling debug env for rc9-3-... to test in live...

**Comment by kozlowski-mathias** [comment]
OK, one more fix:

..., function () { self.checkTemp(); });    // and not    this.checkTemp();    of course :)

But after that, I think we are done!
++Mat
