### ISSUE TITLE
Logical rule definition does not expand devices list at first addition

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#197]
If in a new Logical Rule and trying to add the first condition, I only get a drop down menu with binary selected, but no list with devices. After selecting multilevel and binary again, I do get full editing options

See http://forum.z-wave.me/viewtopic.php?f=3422&t=20961&p=53650#p53645

**Comment by PoltoS** [comment]
This is a known bug of AlpacaJS (JS library we use). We will try to fix it in future

**Comment by pz1** [comment]
Thanks, updated the forum posts accordingly

**Comment by pz1** [comment]
I checked in v2.01. t seems that this issue has been fixed
