### ISSUE TITLE
Configjson not adequately cleaned after element removal

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#203]
After removal of a scene or some other module, it leaves traces in the  automation/storage/configjsonxxxx file. See post http://forum.z-wave.me/viewtopic.php?f=3422&t=21164&p=54597#p54597

**Comment by PoltoS** [comment]
This is by design

**Comment by PoltoS** [comment]
In fact, this is the solution: https://github.com/Z-Wave-Me/home-automation/issues/190
we will do it once
