### ISSUE TITLE
Corrupted de.json file in OpenWeatherExtended Module

### ISSUE THREAD

**Issue by ronie-z-wave** [Z-Wave-Me/home-automation#215]
If you add the module and open the de translated JSON via '/ZAutomation/api/v1/modules/OpenWeatherExtended?lang=de' the german file seems to be limited to 906 signs ... 
I cannot explain but the reason seems to be the content of the 'm_descr' key: 'Der Extended Weather Informer wird unterstützt von OpenWeatherMap.org.'
I have tried to use 'ue' instead of 'ü' but its still the same error ... if I replace the word, with for example 'foobar Ente Teich more words' there will be no error ...
I've stored all lang/*.json in UTF-8 and the error occurs browserindependent.

![mozilla_de-json](https://cloud.githubusercontent.com/assets/10545480/6036870/44e0ae5c-ac4c-11e4-94a1-d15e3708a122.PNG)

**Comment by r3b-fish** [comment]
In the current version, response has a valid json.
I have checked response on http://jsonlint.com and firefox/chrome stable version.

**Comment by r3b-fish** [comment]
Fixed this bug in v2.0.1-rc11.

**Comment by PoltoS** [comment]
@ronie-z-wave please tell us your version of Z-Way

**Comment by ronie-z-wave** [comment]
my Z-Way version is v2.0.1-rc11a

**Comment by PoltoS** [comment]
In that case send us your exact lang file or even full module to let reproduce it

**Comment by ronie-z-wave** [comment]
it is already pushed, you can find the module in or dev branch
