### ISSUE TITLE
internationalization - EN as fallback

### ISSUE THREAD

**Issue by ronie-z-wave** [Z-Wave-Me/home-automation#216]
Maybe it is in already in production:

It will be nice if keys that are not available in ru / de /etc. get the en key as fallback value.
Otherwise the key name would be printed like this \__\KEYNAME\__\ and that looks not like a charm.

**Comment by r3b-fish** [comment]
It is in production.

If language isn't set en,de or ru, then loading en.json, but if en.json isn't found in moduleName/lang/en.json, then loading original module.json.

By the way, language may be set using header Accept-Language

example:
Accept-Language: ru,
Accept-Language: de,
Accept-Language: en

**Comment by PoltoS** [comment]
As I got, the idea is to take en translations if they are not fined in the sepcified langage. This will allow partial translations: non-translated strings will be taken from en.

**Comment by r3b-fish** [comment]
ok)
