### ISSUE TITLE
OpenRemoteHelpers:metrics refining parameter

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#217]
The present code for metrics takes only one parameter [N] ,the device ID:

     case "metrics":
        // used HA API for all device to get metrics
        return this.controller.devices.get(N).get("metrics:level")

If in the last line "level" was filled by the second parameter [I], the function would be more versatile. It would enable not only extraction of the level of a sensor, but also the other attributes.
I could imagine that if the second parameter were omitted, the default "level" attribute was to be returned. That would make the function compatible with earlier releases.

**Comment by pz1** [comment]
It works for me with this code

            case "metrics":
			     // used HA API for all device to get metrics
				 if (I !== "") {
				   attrib = "metrics:" + I;
				   }
				 else {
				   attrib = "metrics";
				   }
                return this.controller.devices.get(N).get(attrib)

In this example I did chose to get all the metrics returned if the second parameter I is omitted.

**Comment by pz1** [comment]
While we are on it we may take the opportunity to
1) Close the Switch construct with a default:
2) Indicate the place where users can safely add their extensions to OpenRemoteHelpers

            case "metrics":
                // used HA API for all device to get metrics
                if (I !== "") {
                  attrib = "metrics:" + I;
                  }
                else {
                   attrib = "metrics";
                  }
               return this.controller.devices.get(N).get(attrib);

     // Your "case" statements may go after this line, but before default:  !
				
			default:
			     return "Error: function " + cmd  + " is not defined in OpenRemoteHelpers";

**Comment by PoltoS** [comment]
good idea to implement this. You can do "pull request" to easily merge it in our main code. Please do in develop branch

**Comment by pz1** [comment]
Done

**Comment by pz1** [comment]
Updated module has been included in develop branch,
