### ISSUE TITLE
Module CodeDevice can not change Sensor scale

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#222]
After editing (v2.0.1-rc10) the Sensor scale, the new value is not displayed, even not after reboot.
In -Preferences/Automation the Sensor scale has taken the new value. On the Dashboard the scale defined at creation is displayed.

**Comment by PoltoS** [comment]
Fixed in rc12

**Comment by pz1** [comment]
Sorry my mistake, but actually I did notice this with v2.0.1-rc12 on my quad core Rapberry 2.
Please consider re-opening

(I was confused with my production Raspberry that runs rc10 at the moment)

**Comment by pz1** [comment]
In the meantime I upgraded my production Raspberry B to rc12, and found the dame problem there. See forum post http://forum.z-wave.me/viewtopic.php?f=3422&t=20964&p=55033#p55033 to see images of HA interface and edit window

**Comment by pz1** [comment]
I just noticed that the problem is fixed in RC14 on my Raspi 2
So the issue can stay closed

**Comment by PoltoS** [comment]
Nice to know. Pay attention, this version is very untested.

**Comment by pz1** [comment]
Thanks for the warning. I alread intended to only use it on my Pi2, which is the testbed
