### ISSUE TITLE
Remove all language from code and move it to lang files

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#223]
Code like this should be replaced by lookup from lang/xx.json files, so that all translations are done in this json file only.
                var message = {
                    "en":"Can not parse yandex jam information.",
                    "de":"Fehler beim Einlesen der Yandex Jam Informationen."
                };

**Comment by ronie-z-wave** [comment]
Yes, of course. It's a module and so it should be instead in /lang/xx.json ... I'll change it.

**Comment by PoltoS** [comment]
Same for main code - please create lang folder and put all translations inside. Again, main code should be translated in one single file.

**Comment by ronie-z-wave** [comment]
Ok, so I will add HA/lang/xx.json for the main code and move the other keys into /MODULE/lang/xx.json

**Comment by ronie-z-wave** [comment]
I have merged my changes into dev-branch after testing. Now there is HA/lang and u can use loadModuleLang(moduleId) or loadMainLang(pathPrefix) via controller to get the lang folder u want. user/Modules translations work well, errors from AutomationController that I can produce too.

**Comment by ronie-z-wave** [comment]
Sry, I don't want to close it :)
