### ISSUE TITLE
Add switchBinary widget for Dimmer

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/home-automation#227]
On including Dimmer (Multilevel switch) only swithcMultilevel is created, it's better to add also switchBinary device. (as it's done in Expert UI)

**Comment by PoltoS** [comment]
if you want to use your dimmer as a switch, you can use CodeDevice module with type switchBinary

It might be also helpful to create dedicated module to do it, may be we will do it soon (see https://github.com/Z-Wave-Me/home-automation/issues/228)
