### ISSUE TITLE
LogicalRule Dimmer dialog should have caption Level not State

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#230]
Imho, in the Logical Rule editor, the Dimmer dialog should have caption **Level** not State
The term State would be better suited for use with enumeration type **mode**

![dimmerstate](https://cloud.githubusercontent.com/assets/7747627/6885145/81104c1c-d612-11e4-866d-8be3eb0c5f6d.PNG)

**Comment by PoltoS** [comment]
Виталий, меняем?

**Comment by PoltoS** [comment]
changed

**Comment by aivs** [comment]
Канэш, могу и по другим молям пробежаться
