### ISSUE TITLE
Z-way - issue with automatic creation of supported CommandClasses

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/home-automation#233]
2.0.1-rc24 ZW500 
Ralated to z-way engine 

I have several devices that have some a  kind of 'phantom' CC that are automatically created after bad data received. They are all created with the following message in Log file.
`Got frame from device 7 to controller, but comm and class 0x4c for  device  is  not registered  -  instantiating  it  as  not  supported`
and are followed by 
`Error returned from  _zway_cc_call_handler(zway,  command,  controller->id,  0, data[4], &data[
5]): Not implemented by
the library (-3)`

May be a validity of recieved frame could be checked  before creating new CC?

**Comment by PoltoS** [comment]
How? If the packet is processed, the CRC is valid. There are no other ways to handle it. But don't care, since it just adds you two-three lines in log - nothing bad
