### ISSUE TITLE
LogicalRule: Request to have the option to select DelayedScene as an Action

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#235]
Don't know how difficult this is, but for reasons of consistency it seems obvious to also have the option to select *DelayedScene*  as **action** in a LogicalRule
See: http://forum.z-wave.me/viewtopic.php?f=3422&t=21468

**Comment by PoltoS** [comment]
LogicalRules is already too complex.

I suggest to make a "clone" of DelayedScene that will create the scene itself (so no need to make a dummy). Or even to modify the current module to allow picking up a scene or creating own (just keep track of backward compatibility to "eat" old config too).

**Comment by pz1** [comment]
Fair enough
