### ISSUE TITLE
Application icon specified in a userModule is not displayed

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#242]
In my [Wunderground module](https://github.com/pz1/home-automation/tree/develop/userModules/Wunderground) I have specified in module.json an icon (png), that is stored in the htdocs folder of that userModule. This icon is not displayed in the Smarthome UI of rc29. Even if I rename the icon to icon.png like it is done in the standard modules, there is still nothing displayed in the apps view of smarthome.

**Comment by ronie-z-wave** [comment]
Hmm usually it should work ... did you create/edit the icon with windows paint? I know that sounds strange, but I've run into the same issue with that tool. Use instead for example gimp or infranview ... If not then I have to debug it :)

**Comment by pz1** [comment]
This Wunderground [icon](https://github.com/pz1/home-automation/blob/develop/userModules/Wunderground/htdocs/wundergroundLogo_4c.png) was taken from their website. I don't know how they made it.
The [icon](https://github.com/pz1/home-automation/blob/develop/userModules/SolQoS/htdocs/solarok58px.png) for my Solar Quality of Service module was mad by myself in Win7 with the program [Paint.NET](http://www.getpaint.net/index.html) not Windows Paint!

**Comment by ronie-z-wave** [comment]
ok, but the other one works?

**Comment by pz1** [comment]
Sorry, both don't work

**Comment by ronie-z-wave** [comment]
Ok, I'll try to find out what the problem is.

**Comment by pz1** [comment]
In the meantime I did move the working OpenRemote icon to my Wunderground userModule. Nothing shows up. There still may be somthing wrong with my icons, but it definitely seems that icons in the usermodules/htdocs folder are not seen.
I'll wait and see. Thanks for your attention.

**Comment by ronie-z-wave** [comment]
argh, sry ...
For the module upload (comes with store in near future) I've added a new param "moduleName" to all module.json's so that we know the correct name for adding and extracting in new folder beneath /usermodules cause 'id' and 'classname' are added by AM-controller after initialization ... So you can solve this by adding this parameter. Nevertheless I think it will be good to have a fallback, e.g. using id or classname instead ... We'll change this ;)

**Comment by pz1** [comment]
Oh eternal joy :)
Thanks; that did the trick! Not a bad idea to add the module name to the module.json file.
(Would be nice if we had a reference document somrwhere decribing all obligatory and optional JSON elements)

**Comment by ronie-z-wave** [comment]
I think during a quite minute I'll try to add this to our wiki: https://github.com/Z-Wave-Me/home-automation/wiki

**Comment by pz1** [comment]
I just documented this on the forum

**Comment by ronie-z-wave** [comment]
thx
