### ISSUE TITLE
V2.0.1-rc40

### ISSUE THREAD

**Issue by anderep** [Z-Wave-Me/home-automation#245]
1) Can't use empty scene in logical rules
2) If you save/update a logical rule to correct the name which now has dropped off due to the software and don't pick a scene to operate on the logical rule will now be broken and the only recourse is to delete the rule.
3) Can't log in with iPhone ZWay app or Z-Way Tablet.
4) Light Scenes can only list up to 19 switches (devices).

**Comment by aivs** [comment]
z-way tablet and zway home control will soon be updated to support the authorization

**Comment by anderep** [comment]
item one is due to the web page only giving you a list that is a subset of what is available, list needs to allow you to scroll thru all devices and scenes
