### ISSUE TITLE
Sonos Module

### ISSUE THREAD

**Issue by Isaksson** [Z-Wave-Me/home-automation#251]
I update Z-Way to version 2.0.1 from RC33 and now the Sonos app is rewritten.

I cant add device by IP anymore and the automatic function with Mute + Volume Up does not work.
Now when the automatic function does not work, what should i type in from my Sonos system?

**Comment by PoltoS** [comment]
Please show the log of startup of HA. It should try to detect Sonos in local network (please make sure RPi is in same network)

**Comment by Isaksson** [comment]
Okey, i have made some more tests now and thing get even more strange.
during my RC33 i had added one of my Sonos devices so i already had one Sonos App running.
I now restarted Z-Way and if i add new Sonos App the list is empty but if i open the one that was created during my RC33 then its filled with 184 of the same household ID.

Where is the HA log that you requested?
This is what i found in the event in HA:
Cannot instantiate module: Sonos: Error: Address already in use

**Comment by PoltoS** [comment]
Please add new app and then delete the old (this will ensure that new gets new ID).

Address already in use means that some app (may be another module or even another Z-Way) occupies port needed for Sonos.

BTW, I'm happy to know someone is using this app! That was not easy to make ;)

**Comment by Isaksson** [comment]
I have now deleted both old and new, restarted Z-Way and now when i add a Sonos App i cant get the household to get filled automatic.
If i now check the events Sonos is not complaining anymore, but that did not solve the issue.

I think we need to check the log file.
Where could i find the log that is in interest. 

I know, i have also made a Sonos app but in C# for another home automation system.
Did you have a big Sonos installation that you tested this app against?

**Comment by PoltoS** [comment]
Only in 3-4 devices. Are you sure they are in same network (LAN)? Check IP address of Sonos and RPi.

After running the module you need to press Plus+Mute as usually.

The bug with many household was fixed - see commit 91c5af2738d27d3c3120205933004400a58ec849

Logs are in /var/log/z-way-server.log

In logs you should search for:
[2015-07-01 01:55:08.995] [I] [core] --- Starting module Sonos
[2015-07-01 01:55:08.997] [I] [core] Waiting for Sonos to send announcement
[2015-07-01 01:55:08.998] [I] [core] Binding Sonos notifier
[2015-07-01 01:55:09.052] [I] [core] Detected own hostname: 192.168.0.184
[2015-07-01 01:55:09.052] [I] [core] Detected AV capable Sonos player on 192.168.0.180
[2015-07-01 01:55:09.053] [I] [core] Creating device switchBinary Sonos_Device_Play_192.168.0.180_9
[2015-07-01 01:55:09.055] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_192.168.0.180_9

**Comment by Isaksson** [comment]
Ahh its the same Log, i though there where an HA log.

[2015-07-01 08:40:12.379] [I] [core] Instantiating module 21 from class Sonos
[2015-07-01 08:40:12.380] [I] [core] --- Starting module Sonos
[2015-07-01 08:40:12.388] [I] [core] Waiting for Sonos to send announcement
[2015-07-01 08:40:12.391] [I] [core] Binding Sonos notifier

When i push Mute + Volume Up

[2015-07-01 08:42:15.053] [I] [core] Detected Sonos Household: Sonos_sXUD1uBYoIZ2J2DXogG2XddBCM
[2015-07-01 08:42:15.136] [I] [core] Detected own hostname: 0.0
[2015-07-01 08:42:15.184] [I] [core] Detected Sonos Household: Sonos_sXUD1uBYoIZ2J2DXogG2XddBCM
And then he continues to find the same Household many times, when i now open HA and check on the Sonos App i now have 46 row with the household.

I have the rpi and sonos on different network but with router in between that permit access between the networks.
The old Sonos module worked with IP and i have not changed the network.

![sonos_zway](https://cloud.githubusercontent.com/assets/4119080/8449078/69760384-1fce-11e5-9de7-3efcbe36f062.PNG)

**Comment by PoltoS** [comment]
[2015-07-01 08:42:15.136] [I] [core] Detected own hostname: 0.0

measns something wrong happened in detection of own IP. Is it always like that? I've noticed that this does not always work for me too, so we will debug it.

And make sure to fetch latest code of Sonos module from git before trying again - the multiple household was fixed in 91c5af2

**Comment by Isaksson** [comment]
I will make some more tests with the latest in develop trunk.
By the way, what do you think about changing version number on app when you make an update, that will make it more easy to keep track on what version we are testing with.
right now its is 1.0.0 stable.

**Comment by PoltoS** [comment]
Indeed, will update soon.

**Comment by Isaksson** [comment]
I have now tested version 1.0.1 with success.
Deleted old Sonos app, restarted z-way, added new Sonos app and pushed Mute+volume up and HA added new elements for every Sonos device.

**Comment by PoltoS** [comment]
Nice to hear!
