### ISSUE TITLE
JSON-Schema for module.json: Fundamental problem?

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#255]
As an option for documenting all the possibilities to configure a module, I thought of defining a json-schema. My main experience is with xmt-dtd and xml-schema, so it's been kind of a culture shock. After a day of playing I must say it remains quite a challenge, since ZWay-modules have a bit more diversity than bookstores;)  Anyhow I got something on the very superficial level.

Unfortunately I did stumble into a fundamental problem if I understand things correctly.

The problem is in the keyword **required**; an obvious choice in the context of javascripting, but problematic for json-schema, since it is a **Keyword** for them. See [specification](http://json-schema.org/latest/json-schema-core.html) Paragraph 2: Conventions.
Actually it looks like a showstopper, since all of the on-line validators that I tested were complaining. 

I'm afraid the keyword **required** in module.json should be replaced by something not conflicting for schema to work. (For my further experiments I can of course use an alternate term)

**Comment by pz1** [comment]
Did not get an answer from the JSON schema guys. Since this is not important for further development, I close the issue.

**Comment by PoltoS** [comment]
Pieter, requires in paragraph 2 refers to a specific meaning in the text of the spec, but not to a keyword in JSON syntax. So this is ok.

Btw, most of module.json is in the format driven by AlpacaJS project. It is well documented
