### ISSUE TITLE
WebInterface: typo in Firmware Updates

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#256]
Web Interface has typo: la**s**test should be **latest** (lastest is archaic spelling)

![update](https://cloud.githubusercontent.com/assets/7747627/8761126/957f7cd8-2d40-11e5-9f78-17fdf5c62b5d.PNG)

**Comment by pz1** [comment]
Same typo? here. If that is your preferred word then please close this issue

![lastest](https://cloud.githubusercontent.com/assets/7747627/9624537/2f25eab2-514e-11e5-8b4e-50e4dc38bddb.PNG)

**Comment by ronie-z-wave** [comment]
Thanks. Typo of button is now correct. Correction in update view is still outstanding.
