### ISSUE TITLE
Security Problem. If connected via find.z-wave.me, the devices are available without a login

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#257]
If connected locally, you need to login to get access to devices (correct).
If connected via find.z-wave.me, the devices are available without a login (not correct).

Local access. Not authorized
<img width="978" alt="2015-07-20 14 56 40" src="https://cloud.githubusercontent.com/assets/2894860/8775461/318d1386-2ef1-11e5-9d86-07ba9b5ce81c.png">

Remote access. Not authorized, but the controller is responsible that authorized
<img width="978" alt="2015-07-20 14 58 36" src="https://cloud.githubusercontent.com/assets/2894860/8775470/4332e6b0-2ef1-11e5-9283-a3ba8a4d17aa.png">

Remote access. Not authorized, but the devices are available
<img width="978" alt="2015-07-20 14 56 45" src="https://cloud.githubusercontent.com/assets/2894860/8775530/cad0391a-2ef1-11e5-8bb8-ef334eef4562.png">

Remote access. Not authorized, rooms not available, the controller responds with an empty array
<img width="978" alt="2015-07-20 14 58 18" src="https://cloud.githubusercontent.com/assets/2894860/8775547/e071e7f0-2ef1-11e5-8b09-bae99752a6d0.png">

**Comment by PoltoS** [comment]
fixed

**Comment by rhearob** [comment]
I see a similar problem locally.  All I have to do is go to:

/ZAutomation/api/v1/devices

to list all of the devices in my server - no authorization required.

**Comment by PoltoS** [comment]
This is because you have local user active and your nginx is local for Z-Way (connects from localhost)
