### ISSUE TITLE
Re: V2.0.2-rc2-beta file configjson-06b2d3b23dce96e1619d2b53d6c947ec.json

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#263]
In this release this json file looks a bit distorted at the end ("id" : 5)

**Comment by PoltoS** [comment]
the file is corrupted?

**Comment by pz1** [comment]
The file does check as valid xml, but does look a bit weird at the end:

}, {
        "id": 4,
        "moduleId": "RemoteAccess",
        "active": true,
        "title": "Remote Access",
        "description": "Is necessary to configure remote access in SmartHome UI.\n(Added by default)",
        "params": {
            "path": "",
            "userId": "",
            "actStatus": true,
            "sshStatus": false,
            "zbwStatus": true,
            "pass": "",
            "lastChange": {}
        },
        "state": "hidden"
    }, {
       "moduleId" : "InfoWidget",
       "active" : "true",
       "title" : "Information for Expert Users",
       "description" : "This is an Information for Expert Users.",
       "params" : {
        "widgets" : [{
          "headline" : "Dear Expert User",
          "text" : "If you still want to use ExpertUI please use this link <strong> >> <a href=\"/expert\">Go to Expert UI!</a> << </strong> <br>\nor call after you are successfully logged in <strong> 'http://MYRASP:8083/expert'</strong> in your browser. <br> <br>\nYou could hide or remove this widget in menu \"Apps > Active Tab\". \n",
          "imgURI" : "/expert/app/images/zplus.jpg"
         }]
       },
       "id" : 5,
       "state" : null,
       "module" : "Informations Widget"
      }]
}

**Comment by PoltoS** [comment]
This is perfectly ok. Just id is not first. Look on it in JSON beautifier.
