### ISSUE TITLE
SmartHome UI does not control locks

### ISSUE THREAD

**Issue by getSurreal** [Z-Wave-Me/home-automation#265]
The SmartHome UI appears to be sending the wrong command for locking and unlocking.  The api command should be 'open' and 'close' but the button click is sending 'on' and 'off'.  The lock works using the Expert UI.

Here's a snippet from the html inspection

```
<button class="btn widget-btn-on btn-sm btn-primary" ng-class="levelVal[v.id]=='open' ? 'btn-primary': 'btn-default'" data-ng-click="levelVal[v.id] = 'open'; runCmd(v.id + '/command/on', v.id)"><i class="fa fa-unlock"></i></button>
```

There's a [thread on the forum](https://forum.z-wave.me/viewtopic.php?f=3422&t=21766&hilit=schlage) that mentions this and there's a comment that says it's fixed for the next revision, but I have installed v2.0.2-rc1 and it is not fixed there.

(btw...the changelog says v2.0.2-rc2, but there is not an install script link with "rc2")

I spent a couple of hours digging around, but I'm not familiar enough to identify where to fix this.  If someone could point me in the right direction, I'd be willing to fix it and submit a pull request.

**Comment by ronie-z-wave** [comment]
hmm strange, this should be fix some months ago (v2.0.1) ... Did you try to clean your browsers cache?

In the latest 'elements.html' I couldn't find your snippet - there it looks correct. Also including doolock (Vision: Z-Wave Door Lock with Handle) and try to lock / unlock  with UI works without a problem.

**Comment by getSurreal** [comment]
I started with a new install at v2.0.1.  

The html snippet I got was from the ui dashboard using developer mode in chrome and right clicking on the button icon to select 'inspect element'.  This reveals the html that is being served using the on/off commands

Does it have anything with how I discovered the device?  I used expert mode for the discovery.  I'll remove the device and rediscover it through the SmartHome UI to see if there's any difference.

**Comment by getSurreal** [comment]
Wishful thinking that discovering it through the SmartHome UI would be any different.  Same issue.  

BTW, this is a schlage door lock and not in the Vision category.  It is properly discovered as a door lock though.

**Comment by ronie-z-wave** [comment]
Ahh ... pardon. I see this bug exists till v2.0.2-rc2-beta. Until this version it is fixed ... So of course you're right :)

At the moment we work hard to complete v.2.0.2. Hopefully we could launch it next week and this bug should be fixed then.

Meanwhile (if you have enough developers experience) you can try to change following lines of code in at your z-way-server on your box:

file in github:
https://github.com/Z-Wave-Me/zwave-smarthome/blob/master/dist/app/views/elements/elements.html      ~line 135

on your box search for 'z-way-server' folder:

and go to
(Rpi: /opt/) z-way-server/htdocs/smarthome/app/views/elements/elements.html  
search for ""

And replace '/command/on' and '/command/off' with '/command/open' and '/command/close' in this block.
save it and refresh the page in your webbrowser.

I wouldn't recomment you to overwrite the whole smarthome folder or elements.html file. Cause then the asynchronus UI and Home Automation Backend could produce new errors ...

**Comment by getSurreal** [comment]
Great!  Thank you.  I've updated it and it's working.

Any estimate when an install script will be available for v2.0.2-rc2?

**Comment by pz1** [comment]
You can always check releases [here](http://razberry.z-wave.me/z-way-server/) Do not use the beta releases unless developers explicitly tell you to do so

**Comment by getSurreal** [comment]
Thanks for the info.  I upgraded to v2.0.2-rc7.
