### ISSUE TITLE
v2.0.2-rc3 Strange behaviour of SwitchControlGenerator with ZME_WALLC_S

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#267]
[See forum](http://forum.z-wave.me/viewtopic.php?f=3422&t=21965) for detailed reports

**Comment by PoltoS** [comment]
bug with exception can be fixed if change
  return el.
to
  return !!el && el.
in automation/modules/SwitchControlGenerator/index.js line 75

Please confirm. This is just due to some empty item in the list of SwitchControlGenerator module config.

The strange naming is certainly due to old device name under same ID (but excluded a long time ago)

**Comment by pz1** [comment]
> return !!el && el

Done, it now reads { return !!el && el.indexOf 
 I do not get the error anymore.
> This is just due to some empty item in the list of SwitchControlGenerator module config

This is how my config looks. Nothing empty afaik
![generate](https://cloud.githubusercontent.com/assets/7747627/9544570/29ffd180-4d82-11e5-9ee7-f1da0bb91393.PNG)
> The strange naming is certainly due to old device name under same ID (but excluded a long time ago)

I only have AEON LABS range extenders.

**Comment by pz1** [comment]
There is still one thing that needs clarification:
ZME_WALLC_S does have 4 buttons. I only get **two** of the  buttons (3 and 4) captured by SwitchControlGenerator. Just for the record: In the device configuration I did *associate* pair 1-2 with a local device.

**Comment by PoltoS** [comment]
By default it allow only two - others need special config param to enable double clicks or separate buttons

**Comment by pz1** [comment]
> By default it allow only two - others need special config param to enable double clicks or separate buttons

Thanks, updated the forum post with this info
