### ISSUE TITLE
v2.0.2-rc3  ImportRemoteHA List of devices not to import

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#268]
I think I reported this somewhere before, but can't locate it right now.

The point is that in this module ImportRemoteHA there is an option to specify which devices **not** to import from **remote side**:
![remote](https://cloud.githubusercontent.com/assets/7747627/9546315/fefbb020-4d91-11e5-8b4f-e7b4bd5371f8.PNG)
However the list that I get presented in this selector are only the **local devices**

**Comment by PoltoS** [comment]
We can not differenciate from local and non-local here in this UI. We will think of it in future. But after import first time you can edit config and here the list will contain many more

**Comment by pz1** [comment]
> But after import first time you can edit config and here the list will contain many more

Adding to the exclude list all the collected devices except for the few that I need, is too akward because of the very long list. (Mind that, in the absence of a modeSwitch, I also have to make 44 code devices for the StellaZ mode sttings)

Tried to delete individual devices of the imported list, since I only need one or two of them. Unfortunately the device I removed seem to get regenerated on the fly. You can't stop that process as you can with the checkbox in the SwitchControlGenerator .
