### ISSUE TITLE
Retain Celsius/Fahrenheit settings during upgrade

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#275]
A user on the forum [states](http://forum.z-wave.me/viewtopic.php?f=3422&t=21880&p=57983#p57983):

>It would be super cool if the upgrade process moved config/defaults.xml or upgrade it. I keep loosing the fahr settings in there and it takes me a while to figure out what happened and then re interview.

**Comment by pz1** [comment]
Asfar as I am concerned, his issue may be closed. I'm no longer following

**Comment by PoltoS** [comment]
This issue also involves other settings retained. User can change many things inside.

If updated via script, it should inform about these changes, but upgrade via UI do not. Unfortunately we can not blindly port user changes from Defaults.xml to the new Defaults.xml, as it can affect Z-Way work.

A three way merge (merge of old original, old by user and new) should be considered.... Let's think how critical is it.

**Comment by islipfd19** [comment]
Is it possible to create a 'Users.xml' where these settings can be defined and then controlled within the management section of the UI? Settings could include but not limited to temperature for Celsius and Fahrenheit and Longitude and Latitude for location?

**Comment by PoltoS** [comment]
Probably let's investigate first, what do people change in their Defaults.xml. May be a poll on the forum?

**Comment by pz1** [comment]
Things I would like to retain that come to mind
- .syscommand settings
- My userCode js files
- My loglevel settings

**Comment by plainsane** [comment]
Yea, I'm pretty sure this was my issue.  I would resort to a simple ugly up that lets me update these settings.  My issue is that after a long time, I forget where the setting is.  It's not a huge issue, but aggregating for us users that use the horrible empirical system.
