### ISSUE TITLE
V2.1.1 IFTHEN Module: correct device description

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#276]
In the device desription text:
> "m_descr":"The If->Then is the foundation of automation. A selected action (WHEN) is executed

The WHEN should be replaced by THEN

**Comment by ronie-z-wave** [comment]
Nope. ;)

'A selected action (WHEN) is executed automatically at the moment when a certain event (IF) has happen.' - think that makes sence

**Comment by pz1** [comment]
Feels twisted to me. This WHEN in capital suggests that it is part of this internal rule terminology, which imho it is not. It would feel better if you left it out all together. 
side note: 'has happen' -> 'has happened'
