### ISSUE TITLE
Sonos App read current state

### ISSUE THREAD

**Issue by Isaksson** [Z-Wave-Me/home-automation#277]
Until today i have only used this Sonos App to send start/stop to some of my Sonos devices, i did now look at the code and it seems that you have a build in function to get the current state for the sonos devices (on or off) but that does not work.
Is that function up and running or is it just a feature that you are working with and that it will be implemented later?

If it should work, then it does not :)
and if it is a upcoming feature :+1:

**Comment by PoltoS** [comment]
What exactly are you talking about? Stop/pause should work

**Comment by Isaksson** [comment]
I am talking about two way communication. Stop / Start a sonos device from your app is working great. But if I start / stop a device from Sonos Android App or direct from a Play 1 then I would like the virtual device to change state. I mean you have already registered against Sonos API upnp so it would be nice to get the current state of the devices.

**Comment by Isaksson** [comment]
So what do you say about this?

**Comment by PoltoS** [comment]
Works for me.

But the UI has some bug - it is not updating. See https://github.com/Z-Wave-Me/zwave-smarthome/issues/58

To check it, refresh the page after changing Sonos state. Will the widget reflect the state correctly?

**Comment by Isaksson** [comment]
If you mean F5 for a refresh then no it does not.
If I debug the sonos app, then i notice that it is fetching the current state for my devices right after a reboot of zway, but after that it does not get any more updates from my Sonos devices.

When i look in the log i find when i turn a device on/off from the zway app but nothing when i change state from Android sonos app or direct on a Play 1.

**Comment by PoltoS** [comment]
Send me wireshark sniffer trace and IP of all devices to filter it. From Z-Way start till change of Play/Pause or Volume in Android app.

Also have a look in notifier function in .onrecv - does it enter inside on unsolicited reports from Sonos? If not, the problem is in wrong IP handling, otherwise it is in onrecv code.

**Comment by Isaksson** [comment]
I have now included wireshark trace and information and mailed it to you, i will take a look at part two in your message tomorrow.

**Comment by PoltoS** [comment]
Looks like we need to update all subscriptions at least every hour. We will add it in our next release

**Comment by PoltoS** [comment]
Please test latest rc6-internal or just fetch 8622282284458eb1a0f510e60380e6947d245c50.
