### ISSUE TITLE
API mismatch to get widgets updateTime and notifications timestamp

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#280]
http://192.168.0.62:8083//ZAutomation/api/v1/devices
For devices used updateTime in number format:
```
{
"creatorId": 22,
"deviceType": "switchBinary",
"h": 1950472924,
"hasHistory": true,
"id": "SecurityMode_22",
"location": 0,
"metrics": {
"level": "on",
"icon": "",
"title": "SecurityMode 22"
},
"permanently_hidden": false,
"tags": [],
"visibility": true,
"updateTime": 1443854700
},
```

http://192.168.0.62:8083//ZAutomation/api/v1/notifications
For notifications used timestamp in string format:
```
{
"id": 1443854468,
"timestamp": "2015-10-03T06:41:08.641Z",
"level": "warning",
"message": "Relay turned on",
"type": "module",
"source": "SecurityMode",
"redeemed": false,
"h": 972347683
}
```
We should use the same format (NUMBER) everywhere.

**Comment by ronie-z-wave** [comment]
The unix timestamp is used as id of notification antry. We also work with that in HA environment. 'timestamp' in notification entry is more a readable visualization of this unix timestamp.
