### ISSUE TITLE
Logging in via API

### ISSUE THREAD

**Issue by rhearob** [Z-Wave-Me/home-automation#290]
I am trying to write a script to log into the z-way-server via the automation API and continuously get this error:

Uncaught TypeError: Cannot read property 'call' of undefined

I am calling via CURL like this:

curl --insecure 'https://user:password@127.0.0.1:8085/ZAutomation/api/v1/login/id=1&role=1&login=home2&password=bridge'

I have my z-way-server behind an nginx reverse proxy using .htpaccess (hence the username and password prior to the server.  The url works - for example, if I list devices by running:

'https://user:password@127.0.0.1:8085/ZAutomation/api/v1/devices'

but I cannot get anything for the login.  I have been unsuccessful in finding any documentation or examples for using the log in.  Any help would be greatly appreciated.

**Comment by PoltoS** [comment]
http://razberry.z-wave.me/index.php?id=13
(search for curl).

Use POST, not GET and use correct URL.
