### ISSUE TITLE
Email&SMS Notification: wrong format check rule of sms.ru API key

### ISSUE THREAD

**Issue by lttn** [Z-Wave-Me/home-automation#292]
sms.ru now have API keys with structure
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}
not
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{8}
____
with 12-chars ended API key  now Email&SMS Notification module does not work.

**Comment by aivs** [comment]
done
https://github.com/Z-Wave-Me/home-automation/commit/4b8101787450a7d9f26331a9b9755c3f012fc141

**Comment by PitBit** [comment]
Hello,
I got 12345678-1234-1234-1234-123456789012, also
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}
not 
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}
can you verified it?
