### ISSUE TITLE
Compliance with IETF RFC2617 HTTP authentication

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#299]
IMHO, Zway does not comply with **IETF RFC2617** *HTTP Authentication: Basic and Digest Access Authentication standard*.
See forum http://forum.z-wave.me/viewtopic.php?f=3422&t=22016&p=59366#p59366

**Comment by pz1** [comment]
Doesn't seem to make sense to keep this active

**Comment by pz1** [comment]
Doesn't seem to make sense to keep this active

**Comment by PoltoS** [comment]
What exactly is wrong?

**Comment by pz1** [comment]
The http authentication of Open remote and ZWay are not compatible. 
In short: OR authenticates fine with Kodi (formerly XBMC) and a range of other products, but not with ZWay as has been discussed at length
