### ISSUE TITLE
No dimmers available in scene configuration

### ISSUE THREAD

**Issue by moroen** [Z-Wave-Me/home-automation#305]
Latest stable 2.2.0.
When trying to create a scene, no dimmers are available in dropdowns. Scenes created before update works, but unable to change levels or add more dimmers. 

I believe this is due to an error in namespaces. When checking namespaces, no one of the multiLevelSwitches are in devices_switchMultiLevel, but they are available in the devices_all namespace. 

{
  "id": "devices_switchMultilevel",
  "params": [
  {
    "deviceId": "DummyDevice_23",
    "deviceName": "Dummy - Multilevel"
  }
 ]
}

{
"id": "devices_all",
"params": [
  {
    "deviceId": "ZWayVDev_zway_2-0-38",
    "deviceName": "Kjøkken - Tak"
  },
  {
    "deviceId": "ZWayVDev_zway_6-0-38",
    "deviceName": "Gang - Tak"
 }
 ]
}

**Comment by moroen** [comment]
A blank reinstall fixed the issue.

**Comment by PoltoS** [comment]
@ronie-z-wave Looks like same I reported recently
