### ISSUE TITLE
Homekit module is missing in v2.2.0?

### ISSUE THREAD

**Issue by tengelmeier** [Z-Wave-Me/home-automation#307]
After an update to 2.2.0 I couldn't configure the homekit module. 
I wanted to delete and recreate the module, but after deletion it is not present any more..

Is the module intentionally removed?

**Comment by PoltoS** [comment]
yes ;(

This was due to Apple. May be it will come back as community module

**Comment by tengelmeier** [comment]
Sad enough. Although I'd appreciate  to learn such stuff from release notes.
Is there an guide / how-to about installing custom modules?

**Comment by pz1** [comment]
> Is there an guide / how-to about installing custom modules?

Store custom modules in folder

z-way-server/automation/userModules
