### ISSUE TITLE
Namespace error when creating new lightscene.

### ISSUE THREAD

**Issue by moroen** [Z-Wave-Me/home-automation#309]
Version 2.2.0, clean install.

When creating a new lightscene using default app, namespace devices_toggleButton:deviceName doesn't get updated when changing title using vDev Widget. Need to open the lightscene setting and save it again, and then the metrics:title and namespace deviceName is synced. 

Steps to reproduce:

Creating lightscene with name "test":

ZAutomation/api/v1/namespaces:
{
  "id": "devices_toggleButton",
  "params": [
  {
    "deviceId": "LightScene_12",
    "deviceName": "Light Scene 12"
  }
  ]
}

So far, expected behavior (I guess, haven't done much research on this previously).

After changing title using widget, the metrics are updated as expected:

ZAutomation/api/v1/devices:
{
"creationTime": 1450218528,
"creatorId": 12,
"deviceType": "toggleButton",
"h": 557861322,
"hasHistory": false,
"id": "LightScene_12",
"location": 0,
"metrics": {
  "level": "on",
  "icon": "",
  "title": "Testing"
},
"permanently_hidden": false,
"probeType": "",
"tags": [ ],
"visibility": true,
"updateTime": 1450218908
}

but the namespace definition is unchanged:

{
"id": "devices_toggleButton",
"params": [
{
"deviceId": "LightScene_12",
"deviceName": "Light Scene 12"
}
]
}

Now, after opening the lightscene settings, and saving the scene again, without making any changes other than pressing "Save", the namespace is updated and showing the deviceName as the same as metrics:title, and the name is displayed in the expected manner in dropdowns where scenes are to be selected.

{
"id": "devices_toggleButton",
"params": [
{
  "deviceId": "LightScene_12",
  "deviceName": "Testing"
}
]
}

**Comment by moroen** [comment]
I just discovered that the same kind of bug affects new devices as well. Recently excluded and reincluded a multilevel switch. The new vDev-widget appeared with its default name (Dimmer (30.0)), changed the title using the widget. The title on the widget updates correctly, but the namespace is still unchanged:

{
"deviceId": "ZWayVDev_zway_30-0-38",
"deviceName": "Dimmer (30.0)"
}

Unlike light scenes,  I haven't found a way to work around this, as saving the widget or opening the underlying device and saving, still doesn't update the namespace.

**Comment by ronie-z-wave** [comment]
will be fixed with next release (since 2.2.1-rc4)
