### ISSUE TITLE
Cron not Working in v2.2.0

### ISSUE THREAD

**Issue by islipfd19** [Z-Wave-Me/home-automation#311]
As the title says, cron is not working in latest stable version 2.2.0. When attempting to edit or add the Cron module an error: ' 404 Not Found. Requested data does not exists' appears on the UI. I have verified that the module and pertinent files do exist in the appropriate directory located at: '/opt/z-way-server/automation/modules/Cron'. There are no relative errors seen in the z-way log file.

Any module dependent on Cron does not function either.

**Comment by pz1** [comment]
There are several other things not working properly in 2.2.0. See forum

**Comment by islipfd19** [comment]
I've performed additional tests, if the cron module was installed prior to v2.2.0 and then zway updated to 2.2.0; cron events work as expected. Obviously, removing Cron and attempting to re-add it will not work. Suggestion for current users that did remove the module after updating to v2.2.0 is to revert back to previous stable build (which is automatically backed up in '/opt' when upgrading to x2.2.0) add the cron module then upgrade using the normal method.

**Comment by pz1** [comment]
On the basis of [this discussion on the forum](http://forum.z-wave.me/viewtopic.php?f=3422&t=22563&p=59877#p59877) I think this issue should not have been closed. Even if the problem description may be incorrect, the problem for users is still there

**Comment by jet11x** [comment]
I was on a previous very and when I upgraded to 2.2.0 scheduled scenes failed to work.  I don't know if cron error related to this, but a rollback (by re-install) to 2.1.1 got the scheduled scenes and cron app working again.

**Comment by ronie-z-wave** [comment]
this issue should be fixed with v2.2.1
