### ISSUE TITLE
Fibaro Universal Sensor no longer auto-updates temperature sensors in v2.2.0

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#313]
Observe the same problem in v2.1.2-rc17

**Comment by PoltoS** [comment]
thanks, already known. we have fixed it and will be part of next rc

**Comment by PoltoS** [comment]
You see this in the log? "...but it is not in channel NIF - ignoring it." If yes, this is fixed. Otherwise it is something new

**Comment by pz1** [comment]
> "...but it is not in channel NIF - ignoring it"

The log is indeed full of it. (A.t.m. FUS is the only device in my v2.2.0 test rig)
I will review and if appropriate close the issue after testing the new RC

**Comment by pz1** [comment]
OK in 2.2.1-rc3
