### ISSUE TITLE
Email&SMS Notification: wrong format check rule of sms.ru API key 

### ISSUE THREAD

**Issue by PitBit** [Z-Wave-Me/home-automation#320]
Hello,
I got 12345678-1234-1234-1234-123456789012, also
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}
not 
[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}

it is possibel add big letters @ key?

**Comment by PoltoS** [comment]
Add many templates in form  "([a-f0-9]{4}-)?" and change a-f0-9 -> a-fA-F0-9

**Comment by PitBit** [comment]
Thanks! It works!

**Comment by PitBit** [comment]
Can You change It for next release?

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/home-automation/commit/12545615afd5f87b50ae5d40d138270e2b02b3e3
