### ISSUE TITLE
Annoying error message in Apps tab if not connected to the internet

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#322]
It should only appear on Local sub tab, but not in Available nor Active sub tabs.

![devsitebug](https://cloud.githubusercontent.com/assets/3664383/13119240/35f12db2-d5b9-11e5-9ea2-84ac8aa6b306.png)

**Comment by ronie-z-wave** [comment]
This api is called in local apps too to visualize if there are a new versions in app store avaiable - app is then marked green (thats maybe not the best way).

**Comment by PoltoS** [comment]
I propose to silently ignore here this error. But show it in Online tab

**Comment by pz1** [comment]
> if there are a new versions in app store avaiable - app is then marked green (thats maybe not the best way).

I was wondering how Maros managed to get a green background in his apps ;) Green generally means safe (Except in Dutch houses from before 1970 where  the green wire carried live 220V!).
If it has to be a color I suggest Orange, so Red could be used for outdated/incompatible

**Comment by MarioGravel** [comment]
I was wondering why some apps had different color. I guess "Update
available" is better than guessing why there are different background.
