### ISSUE TITLE
HTTP chunked reply is invalid

### ISSUE THREAD

**Issue by graycrow** [Z-Wave-Me/home-automation#323]
Z-way API response sets both Content-Length and Transfer-Encoding: chunked. Latest node.js version refuses to process such response with parse error. There is a comment in the one of node.js commits saying that "Cannot use chunked encoding and a content-length header together per the HTTP specification."

**Comment by thexperiments** [comment]
Also blocking me developing a plugin. Any updates?
This renders the API useless when interacting with newer node versions (most likely also other runtimes with decent http parsers).

**Comment by PoltoS** [comment]
Please try this build v2.2.2-test-new-webserver (exists only for Raspberry Pi).

Some functions might not work. Please write here all bugs you see related to the new http server implementation: https://github.com/Z-Wave-Me/z-way-issues/issues/107

I close this issue to move in the latter one
