### ISSUE TITLE
During restore walk thru all online apps used in the config.json and try to download them all

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#324]
http://forum.z-wave.me/viewtopic.php?f=3422&t=22898

**Comment by pz1** [comment]
FWIW: I am drafting a [manual for Backup/Restore in v2.2.1](https://github.com/pz1/ZWayModules/wiki/Zway-Backup---Restore)

**Comment by PoltoS** [comment]
@zwave-mke I think this manual of @pz1 should be included in SH UI

**Comment by pz1** [comment]
@zwave-mke, @PoltoS  Please note that I am not yet finished with the manual.

**Comment by pz1** [comment]
> During restore walk thru all online apps used....

In general this is a good idea, but conflicts may arise if users deploy older versions of these Apps. So maybe this should be a conditional option where the checkbox is ticked by default ? 
Still a general warning message on the restore pop-up would be good

**Comment by PoltoS** [comment]
If user wants older app (his special will), he will make manual copy. By default should use latest apps.

**Comment by pz1** [comment]
Fair enough, that is what I describe in restore manual. But I still think a warning in restore popup would be useful.

**Comment by ronie-z-wave** [comment]
comes with v2.2.2
