### ISSUE TITLE
Z-Wave problem with Raspberry Pi 3

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#330]
There seems to be a hardware conflict with the built-in Wifi/BT on the RaspberryPi 3. See forum http://forum.z-wave.me/viewtopic.php?f=3422&t=22957&p=61270#p61269

**update** There is a kludge to solve this published on the forum.

**Comment by PoltoS** [comment]
No a Z-Way not RaZberry problem. We will update installer to turn off Bluetooth by default. This is Pi 3 h/w "feature"

**Comment by troolee** [comment]
So is there a way to user razberry with BT enabled?

**Comment by ronie-z-wave** [comment]
@PoltoS: Am I right that it should work with UZB or BT dongle? Otherwise it won't ...

**Comment by PoltoS** [comment]
I've heared that in latest Raspbian there is a way to switch BT to the software UART and keep h/w UART for RaZberry. But not sure how.

**Comment by troolee** [comment]
I was able to make BT and zwave controller working on rpi3 using this article http://www.briandorey.com/post/Raspberry-Pi-3-UART-Overlay-Workaround
