### ISSUE TITLE
Question: What is the purpose of App Notification2Storage

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#331]
This App seems to do nothing. For what is it intended?
See http://forum.z-wave.me/viewtopic.php?f=3422&t=22972#p61299
See comment made on the App it self

**Comment by pz1** [comment]
Doesn't seem to make sense to keep this open

**Comment by PoltoS** [comment]
It was intented to save notifications to external storage file instead of JSON in storage/ folder
