### ISSUE TITLE
RaZberry Configuration Interface on port 8084 don't work with new install 2.2.1

### ISSUE THREAD

**Issue by MarioGravel** [Z-Wave-Me/home-automation#336]
I installed a new raspberry Pi II with Razberry chip and when I go on find.z-wave.me and click on the ip address at the bottom, the interface on port 8084 isn't availlable. "Webif is switched off".

As mentionned on forum -> http://forum.z-wave.me/viewtopic.php?f=3419&t=22952#p61401

**Comment by PoltoS** [comment]
Thanks, this is on our radars - we will fix this very soon

**Comment by ronie-z-wave** [comment]
You need to be logged in to use 8084. Now the link redirects you to smarthome UI.

**Comment by MarioGravel** [comment]
Uh... but the session cookie is associated with the host:port ? We can log
on port 8084 now ?

**Comment by MarioGravel** [comment]
I understand that 8084 will be accessible thru 8083 only ?

This is sad...
8084 saved my a**  a couple of times. When you did something wrong (while developing/experimenting) and you jammed 8083, accessing 8084 to call for a reboot/firmware update is very useful. 

Having some kind of "backdoor" access is very useful to debug/help/support others.

I used to work on Tridium/Niagara (JACE) controller. Accessing the platform to debug/fix the station is one of our most powerful tool.

Can we discuss about any possibility to use 8084 directly ? Some backdoor or "super user" access ?

**Comment by PoltoS** [comment]
> Having some kind of "backdoor" access is very useful to debug/help/support others.
And unsecure at the same time ;)

You still can use 8084 after enabling it via SSH access. You can even make it always on - just do via API:
http://localhost:8083/JS/Run/saveObject('8084AccessTimeout', 100000000000);
or via SSH
echo 100000000000 > automation/storage/8084AccessTimeout-6b497208061ec7faae003cdd7f9a035e.json

(100000000000 is just a big number)
