### ISSUE TITLE
Fibaro Universal Sensor: Too high update rates

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#337]
I do notice a very high update rate from my Fibaro Universal Sensor's 4 temperature sensors. In the listing below you will see consecutive readings at 06:25:49.032, 06:25:49.123, 06:25:49.206, 06:25:49.318. For the log details, and device settings, see this [forum post](http://forum.z-wave.me/viewtopic.php?f=3422&t=23010#p61420)

The update rates are not constant over time, even though the parameters that define update rates are all set to default values. On the basis of that I would only expect an update every 200 seconds.

**Comment by PoltoS** [comment]
This looks like FGS problem, not Z-Way. Please report to Fibaro.

Personally I've not seen such behaviour, but I've not tested this much

**Comment by pz1** [comment]
> Personally I've not seen such behaviour, but I've not tested this much

At this moment it would be more helpful for me if you, or anyone who owns a FUS, could provide me here or on the Forum with a log of temperature measurements with FUS parameters 10, 11, and 13 set to their default values: 20, 200, 8
