### ISSUE TITLE
developer.z-wave.me - Module update issues

### ISSUE THREAD

**Issue by MarioGravel** [Z-Wave-Me/home-automation#343]
I uploaded a new version of my module.
The archive section show my new file and my new version (0.1.1 instead of 0.1.0)

The problem is in the description, it didn't update.
I try uploading a version 0.2.0 but no luck.

I try deleting the module and uploading my file to recreate the module but now it's worst: No module at all :-/

It was a module under development, I never asked for verification because it wasn't ready.
I tested the download using token and it worked great !

I wanted to test the "update" function on my Razberry but since the "header" don't update the version number, I wasn't able to try it.

What's next ? How can I recreate my module and continue my tests and development ?

As I'm writing, I'm not able to see any module. The upload works because I can see the file in the module list (http://developer.z-wave.me/modules/) but it is not listed in my home view. Even with new module(different name and updated module.json)

Thanks !

**Comment by vades** [comment]
To test your module try to upload the module directly on your Razberry:
/opt/z-way-server/automation/modules
or
/opt/z-way-server/automation/userModules

Then restart your  Razberry:
$ sudo /etc/init.d/z-way-server restart

**Comment by ronie-z-wave** [comment]
At the moment, it needs to be verified (again and again). So of course this is a point we could discuss. Why to verify a module as long its developer says it isn't ready? We'll think about it.

Also this api makes it a bit faster to reinitialize it from folders ;)

ZAutomation/api/v1/modules/reinitialize/MODULENAME

**Comment by MarioGravel** [comment]
The goodness of developer.z-wave.me was that my associate was able to install the "work on progress" module on his own RaZberry to try new features.

Also, I'm working on the module from the office and want to try the module on my "office RaZberry" and my "home RaZberry" that has a lot more Z-Way devices to experiment with.

So having a token while the module is under development is a great feature/tool.
Also, I like the possibility of putting modules to be offer only to people that know the token.

I'm really looking forward to use this site. I really like what I saw.
I'm very sad that It don't work anymore for me :-/

@vades : That's how I'm working right now. Working local is fine but distant mean opening port (ssh, sftp, 8084, etc). Using the store allowed me to only open port 8083.

@ronie-z-wave : I'm not sure I understand the purpose of `ZAutomation/api/v1/modules/reinitialize/MODULENAME`. It restart the module ?

Thanks and keep on your good work !

**Comment by ronie-z-wave** [comment]
ZAutomation/api/v1/modules/reinitialize/MODULENAME

It first reloads the changed files from folder and restarts the module after ... doing simple stop/start or add/remove doesn't have the same effect, because javascript and json isn't 'refreshed' - the module itself is still marked as 'already loaded'.

Indeed, the using of tokens is e.g. 'share your apps under developement with others' - good for testing and feedback - doing verification everytime during app is under developement will brake this process. 

Thats a good argument to think about the current policy. We'll discuss it intern and keep this post up to date.

Your welcome, thank you for supporting us :)

**Comment by MarioGravel** [comment]
By the way, I'm still stuck with my module issue :-/

My first message wasn't answered.

I mean, I'm testing by uploading directly to my Raspberry but I still can't upload any module in developer.z-wave.me.

I uploaded two : DomotikElectricLog and DomotikElectrik.
Can you "flush" them so I can start over ?

**Comment by zwave-mke** [comment]
Hello,

please send us your module (mk@zwave.eu), we check the upload for you.

BR
mk
