### ISSUE TITLE
Homekit модуль и Siri. Не получается включить конкретное устройство

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#354]
1) Есть 3 устройства с названиями: TV, Люстра, Ночник
Если сказать Siri: "Включи люстру", Siri отвечает: "... в этот раз мне не удалось найти эти устройства".
Если сказать Siri: "Выключи свет", она выключит все бинарные устройства.
Если перевести Siri на английский и сказать: "Turn off TV", Siri отвечает по английски, что не нашла устройство.
Проблема в том, что наш модуль не позволяет Siri управлять устройствами по отдельности.

Также протестировал Homebridge-zway для работы с Homekit, все работает как и нужно.
Если сказать Siri: "Включи люстру", Siri включает реле с русским именем "Люстра".
Если сказать Siri: "Включи TV", Siri включает реле с английским именем "TV".
Если сказать Siri: "Включи ночник на 50%", Siri включает диммер с русским именем "Ночник".
Если расположить устройства по комнатам, то Siri отличает Люстру в Спальне и на Люстру на Кухне.

2) Если переименовать устройство и перезапустить модуль Homekit, то в программе MyTouchHome название устройства не изменяется. Приходится удалять дом в MyTouchHome и заново добавить аксессуар RaZberry.
При использовании Homebridge-zway, если переименовать устройство и перезапустить Homebridge-zway, то имя устройства в реальном времени меняется в MyTouchHome.

**Comment by PoltoS** [comment]
Автор модуля уже всё починил
http://developer.z-wave.me/?uri=public#/web/apps/310
