### ISSUE TITLE
Fibaro Multi Sensor bugs over bugs

### ISSUE THREAD

**Issue by Wikibear** [Z-Wave-Me/home-automation#360]
Hi,

try since a week Fibaro MultiSensor V2.7 to get work well. First start after including all looks well. Time after time, it works or not. Now i have two virtual buttons. The second button show up automatically without anything in touch with me.

If i try to setup MultiSensor via Commands i get empty empty empty values. If i try this via browser i get this in log:

[2016-07-10 16:55:12.423] [I] [zway] Adding job: Configuration Set
[2016-07-10 16:55:12.423] [D] [zway] SETDATA devices.4.instances.0.commandClasses.112.data.60 = Empty
[2016-07-10 16:55:12.423] [D] [zway] SETDATA devices.4.instances.0.commandClasses.112.data.60.val = Empty
[2016-07-10 16:55:12.423] [D] [zway] SETDATA devices.4.instances.0.commandClasses.112.data.60.size = Empty
[2016-07-10 16:55:12.423] [I] [zway] Adding job: Configuration Get

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/16714408/4e7d1862-46c2-11e6-8412-dabf488fe995.PNG)

At first start the device send if motion sensor was activated. Now, nothing happens. Sometimes if i accelerate the device i get a all information.

This is a picture. Check windows time to moving and motion and alert time.

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/16714320/7314aa62-46bf-11e6-89ab-cf26a3434df7.PNG)

Now you can say, yes the sensor is miles away from basestation... Nope... I try it out and put sensor in a range within 2-3 meters. But... nothing happens. Normally the sensor must send every 300 seconds a signal for wakeup... This will be also not done. 

After new interview maybe things will work. But all set commands will not read out. If i configure this into the sensor this settings must be stay I think. Correct me if I'm wrong.

If you have questions don't hesitate to contact me.

**Comment by PoltoS** [comment]
To configure the sensor you need to wake it up.

**Comment by Wikibear** [comment]
Yes i do that. That works now after restart. Before i get empty emtpy emtpy same what my pictures says.

But i have two virtual button and moving via acceleration X Y and via body will not be displayed or updated. The log doesn't show anything about my device 4 within this action.

I set temp and lumi to 300sec wakeup. It's green now! But nothing happens. If I wait 5 minutes no updates will received.

**Comment by PoltoS** [comment]
I see here

`[2016-07-10 19:33:48.704] [I] [core] Notification: device-info (device-OnOff): {"dev":"Fibar Group (4.1.1) Button","l":"on"}`

Means "On" event was trapped.

CRC error seems to be device problem: limunance report CRC mismatch.

**Comment by Wikibear** [comment]
Yes that's right after 12h nothing changed here. Look at the next picture with reference of windows clock.
![unbenannt](https://cloud.githubusercontent.com/assets/18314278/16720357/d682f448-4735-11e6-868f-7989b2d888b6.PNG)

**Comment by Wikibear** [comment]
I have news. :)
The big problem at my sensor is the range to controller. I use now the sensor within 2,5 to 3 meters and it's seem to be working now. But i have some issue with device descriptions. Cant send temperature well only via expert commands:
https://forum.z-wave.me/viewtopic.php?f=3422&t=20393&p=62884#p62884

**Comment by PoltoS** [comment]
I will close this issue as it is too sporadic and mixes many-many bugs in one. Looks like the new firmware from Fibaro have some troubles, but it is not clear yet what exactly. While some of the reported bugs are just misunderstending.

Like 300 sec is not "report time", but wakeup time - means device should just wake up to allow reconfiguration, but must not report all it's values.
