### ISSUE TITLE
Problems with localhost user

### ISSUE THREAD

**Issue by Wikibear** [Z-Wave-Me/home-automation#361]
Hi,

i have some problems with localhost user.

First i can't reach the api without login. Room is set and the user via localhost is set, but i get an error to talk with api.
Then i delete localhost user (something what i not need to do i think) and want to try to add a new user. Passwort fields are required for this user and its unable to add a user without password.

How can i fix this issue to add a new localhost user without password?

Firmware 223rc3 is in action.

**Comment by PoltoS** [comment]
Just add the user with any password. It will not be used once accessed from localhost (127.0.0.1).

PS

----- Исходное сообщение -----

**Comment by Wikibear** [comment]
But if i try this i get 401 Unauthorized error.

**Comment by PoltoS** [comment]
Make sure to execute http://localhost:8083/ZAutomation/api/v1/session first and save the cookie to use in future requests.


----- Исходное сообщение -----

**Comment by ronie-z-wave** [comment]
that issue will be closed, because there seems to be no more question or comments
