### ISSUE TITLE
Network Error 409 Unable to update data

### ISSUE THREAD

**Issue by Wikibear** [Z-Wave-Me/home-automation#363]
After fresh added devices with v.2.2.3 and i want to add a device to dashboard i get follow error: Unable to update data.

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/16867981/4feeac04-4a75-11e6-8018-1f6b8a2ed109.PNG)

Investigation of network traffic via Firebug push out this:

![unbenannt2](https://cloud.githubusercontent.com/assets/18314278/16867980/4fedbd4e-4a75-11e6-9d86-95d0b4f5a85a.PNG)

No device will put on my dashboard.

**Comment by ronie-z-wave** [comment]
hmm, could you please check that you are not using same email adress on different users?

**Comment by Wikibear** [comment]
How can i investigate that?

**Comment by ronie-z-wave** [comment]
Please go to Menu > Management > User management in Smart Home UI, and check each user by editing them

**Comment by Wikibear** [comment]
OK, at the moment i have only Administrator and Local User. Administartor setup with my email adress. No other user. Before i reset all to factory settings. Maybe there was no full reset?

**Comment by ronie-z-wave** [comment]
OK if also Local User has no or an other e-mail address then there seems to be something strange.

You could also check via ssh what is written in /opt/z-way-server/automation/storage/configjson-*.json under "profiles":[...]

Usually the server will load the stored entries from this configjson-*.json on every startup. A restore will  load the default ones and overwrite the current.

Do you use local access via 127.0.0.1? 
And with which user are you logged in, Administrator or Local User?

**Comment by Wikibear** [comment]
OK, my email adress is only once a time in config. NOT twice. I'm usingmy admin account for login. I logged in via 192.168.X.X. Not via Localhost.

**Comment by ronie-z-wave** [comment]
Hmm ok ... what happens after you've cleaned the cookie for 192.168.X.X? Does it work then?
Maybe also cleaning browsers cache and doing page reload (ctrl+F5) is worth a try.

**Comment by Wikibear** [comment]
Delete Cache Cockie by hand and problem is solved. 
Thanks for support!

**Comment by ronie-z-wave** [comment]
You're welcome :)
