### ISSUE TITLE
v2.2.4-rc2 : This release still installs readKey

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#368]
Release v2.2.4-rc2 still installs **readKey**.  This process takes quite a bit (15-20%) of CPU time itself for doing nothing, but my overall impression is that also z-way-server is using 20-30% more CPU than without **readKey**. (observed on RaspiB/RaZberry-Gen3; later also on Raspi2/UZB1)
On what is said at the end of [this issue 105](https://github.com/Z-Wave-Me/z-way-issues/issues/105), I think it should not be installed anymore

**Comment by PoltoS** [comment]
Finally removed it from installer
