### ISSUE TITLE
App names not translated on tab Active 

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#371]
<img width="1280" alt="2016-08-02 18 32 36" src="https://cloud.githubusercontent.com/assets/2894860/17334603/7f3cf8b2-58df-11e6-828f-dbda43dc3a38.png">

**Comment by PoltoS** [comment]
Because these are not apps names, but instances names. They are not translated.

**Comment by aivs** [comment]
Ну и почему имя по умолчанию должно быть не таким как название приложения его создавшего. Имя по умолчанию берется из en.json. Это именно имя приложения!!!

**Comment by PoltoS** [comment]
а ты уверен? просто ты создавал их с английской локалью. А вновь созданные в интерфейсе РУС будут скорее всего на русском. Не? Ведь перевод делает сервер.

Или просто у нас default title не переводится - такое может быть

**Comment by aivs** [comment]
Ты прав, какой язык был включен, такой перевод и используется.
