### ISSUE TITLE
Apple HomeKit Gateway no connection

### ISSUE THREAD

**Issue by BoxSo** [Z-Wave-Me/home-automation#377]
I'd set up the apple HomeKit App. The app worked for two days and now all iPhones regret to connect to my RazBerry. 

If i open the "Home" App at my iPhone and add a device i can type in the code which is shown within the Apple HomeKit Gateway App configuration dialog. 
Then after some seconds, my phone tells me that Razberry could not be added cause the connection to the device could not be established.

Firmwareversion v2.2.3
UI Version  1.4.3
iOS Version    10

any ideas? Are there logs i can get some more detailed information from?

**Comment by iNorD** [comment]
Same issue! 

![img_1584](https://cloud.githubusercontent.com/assets/2789261/18779127/3e7a1ff2-8180-11e6-8b6e-877efffaf0e4.PNG)

**Comment by BoxSo** [comment]
Is there a way to get more detailed logging information ?
I can not see any log entries while trying to connect from an iphone.

**Comment by BoxSo** [comment]
Nobody can assist in diving into details how to debug this?

**Comment by ronie-z-wave** [comment]
Since we've removed it from home-automation repository at the begining of the year HomeKitGate is managed as a third party app. We've tried to contact the developer but unfortunately he seems to be inactive since a while ...

**Comment by PoltoS** [comment]
Looks like the developer has released a new version. Please have a look on the store:
http://developer.z-wave.me/?uri=public#/web/apps/310
