### ISSUE TITLE
Postfix issue with Popp smoke sensor?

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#378]
I can't get my Popp smoke sensor selected in the Fire Protection app. (see [forum post](http://forum.z-wave.me/viewtopic.php?f=3419&t=23470&p=63896#p63896))
The postfix spec for this device lists amongst others
"noVDev,0-113"
I assume that this prevents ZWay to create this virtual sensor, which is a necessity for the Fire Protection app to "see" the device. Why? or is something else wrong. I recently purchased three of these devices, and they all behave the same (ZWay 2.2.4-rc9)

**Comment by ronie-z-wave** [comment]
Hi,

I've replied to your [forum posts](http://forum.z-wave.me/viewtopic.php?f=3419&t=23470&p=63955#p63955).

**Comment by pz1** [comment]
Thanks for your quick response. I've reported back to the forum that things are working now.
closing
