### ISSUE TITLE
Adding Accept_type authorization

### ISSUE THREAD

**Issue by BoxSo** [Z-Wave-Me/home-automation#379]
To be able to make ajax requests from other devices within network and deal with CORS in modern browsers, "Authorization" should be added to the list of access_types reported by Z-Way to the requesting client.

If i add the entry "Authorization" within the code to the list, it works like a charm.

**Comment by PoltoS** [comment]
You can make a pull request (to dev branch) or we can add it

**Comment by BoxSo** [comment]
tried to make a pull request. Git says i'm not allowed to do that?

**Comment by BoxSo** [comment]
![bildschirmfoto 2016-09-26 um 20 27 42](https://cloud.githubusercontent.com/assets/3858285/18846770/ccc12d42-8427-11e6-90c0-dcd4dae14d69.png)

The change is not that big so it might be easier to have somebody insert the line of code :)

**Comment by PoltoS** [comment]
done
