### ISSUE TITLE
Errors installing on fresh Raspberry Pi 3 with Jessy Lite 

### ISSUE THREAD

**Issue by JorritPosthuma** [Z-Wave-Me/home-automation#386]
Just so you know, I had some errors during install, and wanted to share them with you. I hade an fresh Rasbian Jessy install (updated), and got the following errors:

```
### only showing the end of the log
!!! Update Raspberry Pi 3 Firmware for stability work with commands:
sudo apt-get install rpi-update
sudo rpi-update
ls: cannot access config/zddx/*.xml: No such file or directory
Usage: ./z-cfg-update <filename>
diff: /etc/inittab: No such file or directory
diff: /tmp/zway_install_inittab: No such file or directory
Preparing AMA0 interface:
 removing 'console=ttyAMA0,115200' and 'kgdboc=ttyAMA0,115200 and 'console=serial0,115200' from kernel command line (/boot/cmdline.txt)
 removing '*:*:respawn:/sbin/getty ttyAMA0' from /etc/inittab
mv: cannot stat ‘/tmp/zway_install_inittab’: No such file or directory
AMA0 interface reconfigured, please restart Raspberry
```

Se server is working fine afterwards (except for missing the device profiles I think).

**Comment by pz1** [comment]
Similar errors here at the end of the install log on Raspi2. I did make a new install. Have not yet tried to add devices to it

**Comment by PoltoS** [comment]
Looks like we are not handling new systemd.
@aivs Please check it

**Comment by zain** [comment]
Same error here using Jessie Lite 2017-01-11.

**Comment by aivs** [comment]
It's not a problem. Install script works with old and new Jessie. In new Jessie these files have not, so to configure AMA interface used another algorithm. 
In future I'll make this script more clean, and it will not print these messages.
