### ISSUE TITLE
changing admin password and not entering admin locks the user with null login

### ISSUE THREAD

**Issue by justinasjaronis** [Z-Wave-Me/home-automation#399]
When I enter to user management form and try to change administrator password, it provides login name field, which is somewhy null by default.

When I enter password and click submit, login is being set to null and it's impossible to log in with this user anymore, unles changing login in /opt/z-way-server/automation/storage/*.json.

The form shouldn't change login if it is empty or at least should provide current login in the field.

**Comment by ronie-z-wave** [comment]
Hi,

could you please share a screen with us from **Management > Usermanagement > Your Admin Profile** and please also send some information about the z-way / ui version? You'll find it under **Management > Info**

We couldn't reproduce this in our current stable version v2.2.5.

**Comment by justinasjaronis** [comment]
You are right, after firmware upgrade it is fixed. Sorry for disturbance. 

P.S. it would be good idea to update image with latest version, because new version has a lot of new features.. And old image didn't work for me on Raspberry Pi 3.

**Comment by ronie-z-wave** [comment]
@PoltoS 

> P.S. it would be good idea to update image with latest version, because new version has a lot of new features.. And old image didn't work for me on Raspberry Pi 3.

**Comment by PoltoS** [comment]
We have just finished a new image. You got it yesterday.
