### ISSUE TITLE
Differenciate Dimmer from Blind in ZWaveGate

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#40]
Using DeviceClass

**Comment by pz1** [comment]
I can indeed do with custom icon. (A reasonable type of device would be **valve**. I haven't seen that in the context Z-Wave yet.)

**Comment by PoltoS** [comment]
We will have custom icons soon. But still default icon is good to have different for blinds and dimmers.

By the way, it should work. Check this line doing it:
https://github.com/Z-Wave-Me/home-automation/blob/4d110dfa2cecb7cee65be67558aa4fadf2be56eb/modules/ZWave/index.js#L1052

**Comment by PoltoS** [comment]
We will have customized icons soon. So this will be solved.
