### ISSUE TITLE
API call for setting config param doesn't work

### ISSUE THREAD

**Issue by kvolden** [Z-Wave-Me/home-automation#402]
The API call `zway.devices[n].Configuration.Set(i, j, k)`, passed in the url of a HTTP request, doesn't seem to work like expected. From my understanding, the call should set device n's parameter i to the value j specifying k bytes, but that's not what it does. Instead it makes the Expert UI say that the value has been updated to 1 (not the value here represented by j), but not written to the device yet.

Tried on Razberry with version 2.2.4 .

**Comment by PoltoS** [comment]
The API call works perfectly. May be seomthing in Expert UI? Sure your device is not sleeping?

**Comment by kvolden** [comment]
This is very strange. I've tried it a hundred times and got the results described above (on a dimmer, so not sleeping), but now it works. Sorry. I'll just close this and will get back to you if I'm able to reproduce the error.

Thanks. :)
