### ISSUE TITLE
ZAutomation API authentication

### ISSUE THREAD

**Issue by archpoint** [Z-Wave-Me/home-automation#409]
Hi.

Looking at the Z-Way/ZAutomation API documentation it seems like there is no way to handle authentication at all? Searching around the only solution that seems to be viable is to authenticate manually and save a session cookie and use that for subsequent requests which is a really cumbersome solution.

Is there any work being done to add authentication features to the API at all?

**Comment by ronie-z-wave** [comment]
Hi,

you are also able to use simple Basic Authentication within your api requests. This should give you full API functionalities depending on user role restrictions.

**Comment by archpoint** [comment]
@ronie-z-wave Ah, cool! That helps :) Thanks!
