### ISSUE TITLE
Climate control - continuous readjustment during polling interval 

### ISSUE THREAD

**Issue by Kratax** [Z-Wave-Me/home-automation#416]
Although set to 19° in schedule (based on time), the logs contain set to 20° (comfort temperature) and reset after a minute to 19°. Additionally, interval planned for time 6:00-21:00, i.e. no change needed during below mentioned time slots.

Event logger:
09:49 | Danfoss Thermostat Heat is 19 °C device-status
09:48 | Danfoss Thermostat Heat is 20 °C device-status
09:39 | Danfoss Thermostat Heat is 19 °C device-status
09:38 | Danfoss Thermostat Heat is 20 °C device-status
09:29 | Danfoss Thermostat Heat is 19 °C device-status
09:28 | Danfoss Thermostat Heat is 20 °C device-status
09:19 | Danfoss Thermostat Heat is 19 °C device-status
09:18 | Danfoss Thermostat Heat is 20 °C device-status

![climate settings](https://cloud.githubusercontent.com/assets/25452697/22458213/b5a5a66a-e79b-11e6-8bb7-df30afec0b51.png)

**Comment by ronie-z-wave** [comment]
Hi,
does this happen every day or only on su/mo and fr/sa? My guess is it happens on mo ...

**Comment by Kratax** [comment]
Hi,
that log is actually from Tuesday... will check again tomorrow but currently does not seem to be related to su/mo...

**Comment by lukaskog** [comment]
The same here. This is probably also causing, that Automation Resettime parameter (is set to 1 hour) is not working - this means, that when I change a temperature locally on the valve, it stays unchanged until next next schedule time comes in place (might be several hours). 
This is my log from yesterday (I changed temperature manually localy to 6C at cca. 19:30):
device-status	30.10. - 22:16 | kurenie obyvacka is 22 °C	
device-status	30.10. - 22:15 | kurenie obyvacka is 6 °C	
device-status	30.10. - 22:11 | kurenie obyvacka is 22 °C	
device-status	30.10. - 22:10 | kurenie obyvacka is 6 °C	
device-status	30.10. - 22:06 | kurenie obyvacka is 22 °C	
device-status	30.10. - 22:05 | kurenie obyvacka is 6 °C	
device-status	30.10. - 22:02 | kurenie obyvacka is 22 °C	
device-status	30.10. - 22:01 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:57 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:56 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:52 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:51 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:47 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:46 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:42 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:41 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:37 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:36 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:32 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:31 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:27 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:26 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:22 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:21 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:17 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:16 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:12 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:11 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:07 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:06 | kurenie obyvacka is 6 °C	
device-status	30.10. - 21:02 | kurenie obyvacka is 22 °C	
device-status	30.10. - 21:02 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:58 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:57 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:53 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:52 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:48 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:47 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:43 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:42 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:38 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:37 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:33 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:32 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:28 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:27 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:23 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:17 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:13 | kurenie obyvacka is 22 °C	
device-status	30.10. - 20:12 | kurenie obyvacka is 6 °C
device-status	30.10. - 20:07 | kurenie obyvacka is 6 °C	
device-status	30.10. - 20:03 | kurenie obyvacka is 22 °C	
device-status	30.10. - 19:58 | kurenie obyvacka is 6 °C	
device-status	30.10. - 19:53 | kurenie obyvacka is 22 °C	
device-status	30.10. - 19:48 | kurenie obyvacka is 6 °C	
device-status	30.10. - 19:44 | kurenie obyvacka is 22 °C	
device-status	30.10. - 19:38 | kurenie obyvacka is 6 °C	
device-status	30.10. - 19:34 | kurenie obyvacka is 22 °C	
device-status	30.10. - 19:33 | kurenie obyvacka is 6 °C	
device-status	30.10. - 19:33 | kurenie obyvacka is 20.5 °C	
device-status	30.10. - 19:29 | kurenie obyvacka is 22 °C	
device-status	30.10. - 19:28 | kurenie obyvacka is 20.5 °C	
device-status	30.10. - 19:24 | kurenie obyvacka is 22 °C

**Comment by ronie-z-wave** [comment]
Hi,

we could already find the cause and are trying to implement a solution for that.
Thank's for your feedback.
