### ISSUE TITLE
Please check that doorlock vDev is updated on lock manual operation

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#426]
http://forum.z-wave.me/viewtopic.php?f=3423&t=24624#p67716

**Comment by kvolden** [comment]
I'm the one who started the thread, and would like to add that the vDev doesn't update it's status to open even when I use the web interface or api to open the lock. The actual physical lock turns and opens like expected, but the vDev status remains at "close".

Logs for both use cases are in the thread.

**Comment by PoltoS** [comment]
Looks fixed (in v2.3.1). Please confirm:
https://github.com/Z-Wave-Me/home-automation/commit/f39c5ffa4cf9a1fd49521af747053a305429bd8f

**Comment by kvolden** [comment]
It works again in version 2.3.1.

**Comment by ToddGreenfield** [comment]
Hi. This is not working for me. I just updated to 2.3.1 and while this update solved the problem of not showing a status in the smarthome UI (which it does now) https://github.com/SphtKr/homebridge-zway/issues/103, the new problem is when the lock auto-locks or I manually change lock states it does not update the smarthome UI. Additionally, in the expert UI I no longer see the lock in the Control/Locks section. It just disappeared from that screen, but the lock still shows on the others as well as the smarthome UI.
