### ISSUE TITLE
Sonos Module - Can not make request: Internal Server Error and system hangs

### ISSUE THREAD

**Issue by austinmroczek** [Z-Wave-Me/home-automation#434]
I have two Play 1 Sonos devices working properly on my LAN.  I enabled the Sonos Module.  It recognizes the devices and seems to work o.k.  Come back a few hours later and entire Z-Way has hung (server process was still running but web UI was not serving pages and no automation tasks were done).  

Some key log entries:

143087:[2017-06-17 16:15:00.510] [I] [core] ---  Sonos_Device_Play_192.168.1.11_53 performCommand processing: {"0":"update"}
143088:[2017-06-17 16:15:00.512] [I] [core] ---  Sonos_Device_Volume_192.168.1.11_53 performCommand processing: {"0":"update"}
143089:[2017-06-17 16:15:00.515] [I] [core] ---  Sonos_Device_Play_192.168.1.9_53 performCommand processing: {"0":"update"}
143090-[2017-06-17 16:15:00.517] [D] [zway] SENDING (cb 0x22): ( 01 09 00 13 09 02 26 02 25 22 CD )
143091:[2017-06-17 16:15:00.518] [I] [core] ---  Sonos_Device_Volume_192.168.1.9_53 performCommand processing: {"0":"update"}
143092-[2017-06-17 16:15:00.519] [D] [zway] RECEIVED ACK
143093-[2017-06-17 16:15:00.523] [D] [zway] RECEIVED: ( 01 04 01 13 01 E8 )
143094-[2017-06-17 16:15:00.524] [D] [zway] SENT ACK
143095-[2017-06-17 16:15:00.524] [D] [zway] Delivered to Z-Wave stack
143096:[2017-06-17 16:15:00.542] [I] [core] [Sonos.prototype.action] Can not make request: Internal Server Error
143097:[2017-06-17 16:15:00.542] [I] [core] [Sonos.prototype.action] host: 192.168.1.11
143098:[2017-06-17 16:15:00.542] [I] [core] [Sonos.prototype.action] action: Pause
143099:[2017-06-17 16:15:00.544] [I] [core] [Sonos.prototype.action] Can not make request: Internal Server Error
143100:[2017-06-17 16:15:00.544] [I] [core] [Sonos.prototype.action] host: 192.168.1.9
143101:[2017-06-17 16:15:00.544] [I] [core] [Sonos.prototype.action] action: Pause

143125:[2017-06-17 16:16:00.761] [I] [core] ---  Sonos_Device_Play_192.168.1.11_53 performCommand processing: {"0":"update"}
143126:[2017-06-17 16:16:00.765] [I] [core] ---  Sonos_Device_Volume_192.168.1.11_53 performCommand processing: {"0":"update"}
143127-[2017-06-17 16:16:00.769] [D] [zway] SENDING (cb 0x23): ( 01 09 00 13 09 02 26 02 25 23 CC )
143128-[2017-06-17 16:16:00.771] [D] [zway] RECEIVED ACK
143129:[2017-06-17 16:16:00.771] [I] [core] ---  Sonos_Device_Play_192.168.1.9_53 performCommand processing: {"0":"update"}
143130:[2017-06-17 16:16:00.774] [I] [core] ---  Sonos_Device_Volume_192.168.1.9_53 performCommand processing: {"0":"update"}
143131-[2017-06-17 16:16:00.775] [D] [zway] RECEIVED: ( 01 04 01 13 01 E8 )
143132-[2017-06-17 16:16:00.775] [D] [zway] SENT ACK
143133-[2017-06-17 16:16:00.776] [D] [zway] Delivered to Z-Wave stack
143134:[2017-06-17 16:16:00.802] [I] [core] [Sonos.prototype.action] Can not make request: Internal Server Error
143135:[2017-06-17 16:16:00.802] [I] [core] [Sonos.prototype.action] host: 192.168.1.11
143136:[2017-06-17 16:16:00.803] [I] [core] [Sonos.prototype.action] action: Pause
143137:[2017-06-17 16:16:00.858] [I] [core] [Sonos.prototype.action] Can not make request: Internal Server Error
143138:[2017-06-17 16:16:00.858] [I] [core] [Sonos.prototype.action] host: 192.168.1.9
143139:[2017-06-17 16:16:00.859] [I] [core] [Sonos.prototype.action] action: Pause

143170-[2017-06-17 16:17:00.967] [I] [core] ---  ZWayVDev_zway_19-0-64 performCommand processing: {"0":"update"}
143171:[2017-06-17 16:17:00.968] [I] [core] ---  Sonos_Device_Play_192.168.1.11_53 performCommand processing: {"0":"update"}
143172:[2017-06-17 16:17:00.970] [I] [core] ---  Sonos_Device_Volume_192.168.1.11_53 performCommand processing: {"0":"update"}
143173:[2017-06-17 16:17:00.974] [I] [core] ---  Sonos_Device_Play_192.168.1.9_53 performCommand processing: {"0":"update"}
143174:[2017-06-17 16:17:00.977] [I] [core] ---  Sonos_Device_Volume_192.168.1.9_53 performCommand processing: {"0":"update"}

<<<<<and this is where log entries stopped and the systems appears to be hung>>>>>>>

Note:  I added the "[Sonos.prototype.action]" as debug code to try to narrow it down.  This is telling me the error is in the Sonos.prototype.action function.

Firmware version	v2.3.1
UI version	1.7.0-RC-9
Built date	23-03-2017 16:30:33

**Comment by PoltoS** [comment]
This means Sonos returns 500 error. Not sure it is a problem of Z-Way. Was that solved for you?

**Comment by austinmroczek** [comment]
Sorry I should have closed this issue sooner.  I briefly just turned off the Sonos automation, but then I moved to a different home automation solution.
