### ISSUE TITLE
Sonos Module: Forward, Backward Button

### ISSUE THREAD

**Issue by vuza** [Z-Wave-Me/home-automation#444]
Hi, I connected my Sonos speaker to the z-wave.me platform via the Sonos app. Play/Pause and Volume works fine, but I cannot find any forward/backward functionality.

I got 2 buttons, with the following IDs: "Sonos_Device_Volume_.." and "Sonos_Device_Play_.."

How many virtual buttons should be created? Where am I supposed to look for this functionality?

Maybe @PoltoS knows?
Any help is highly appreciated!
Tx

**Comment by PoltoS** [comment]
Only Play/Stop and Volume are created. You can alter the module to add more buttons and corresponding hooks and commands to Sonos

**Comment by vuza** [comment]
Okay, thank you! Any idea where I can find a list of possible commands I can pass to the action function? https://github.com/Z-Wave-Me/home-automation/blob/master/modules/Sonos/index.js#L318

Searching on Google wasn't really successful.

**Comment by PoltoS** [comment]
I used tcpdump for that ;)

**Comment by vuza** [comment]
Would you accept PRs for Next, Previous, etc. functionality if well implemented?

**Comment by PoltoS** [comment]
Sure! Your contribution is welcome!

**Comment by vuza** [comment]
et voilà https://github.com/Z-Wave-Me/home-automation/pull/446

**Comment by PoltoS** [comment]
Merci!
