### ISSUE TITLE
Show if device is dead

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#447]
In smarthome ui impossible to understand that device is dead. Need to show this like fibaro.
<img width="395" alt="2" src="https://user-images.githubusercontent.com/2894860/29964808-fad9185a-8f13-11e7-927e-623000daa7a0.png">

**Comment by PoltoS** [comment]
Implemented in ec52880c0d6ed897468e4b27cf6e964e826d2269 and other commits
