### ISSUE TITLE
find.z-wave.me immediately redirects back to remote login

### ISSUE THREAD

**Issue by kvolden** [Z-Wave-Me/home-automation#457]
When going to https://find.z-wave.me/zboxweb and entering the remote id and password, the site redirects to the local gateway, but before the local login page has even completed loading, it immediately redirects back to the remote login page.

For a while, it was possible to press the browser stop button at the exact right moment (usually taking a lot of attempts) to stop the loading of the local login, and prevent the redirect back to the remote login page, but for some reason this doesn't seem to work anymore.

Forum thread on this here: https://forum.z-wave.me/viewtopic.php?f=3422&t=25489

**Comment by PoltoS** [comment]
could you provide more info about your acoont to let us try it? please send directly to info@ or ps@

**Comment by kvolden** [comment]
Sent by email to ps@...

**Comment by kvolden** [comment]
I received a reply from PoltoS. If instead of using the approach of entering remote id and remote password, one puts in the local credentials with the username prefixed with "ID/", without quotes, where ID is the remote ID, it works.
