### ISSUE TITLE
Unchecking Active checkbox does nothing

### ISSUE THREAD

**Issue by ToddGreenfield** [Z-Wave-Me/home-automation#466]
In the Smarthome UI under Apps and using the Periodical Switch Polling app as an example (I got the same results with multiple apps), after clicking PeriodicSwitchPolling, then unchecking the 'Active' checkbox to temporarily disable, then clicking save, the screen refreshes the page but the checkbox is still checked. It does nothing. No errors appear in the browser and the z-wave-server.log shows:
[2017-04-16 10:26:07.070] [I] [core] --- Stopping module Periodical Switch Polling
[2017-04-16 10:26:07.072] [I] [core] --- Starting module Periodical Switch Polling

If on the Active Apps page, if you click the middle flame button (Activate/Deactivate), then it will work. It seems the checkbox on the specific PeriodicSwitchPolling page is just an indicator, if so, it should not be checkable/uncheckable.

**Comment by karei90** [comment]
Fixed in https://github.com/Z-Wave-Me/home-automation/commit/2f569850a686300955c08f409023b5003204a96c
