### ISSUE TITLE
developer.z-wave.me: Upload of module package fails with error

### ISSUE THREAD

**Issue by ralphwetzel** [Z-Wave-Me/home-automation#474]
Hi!
I tried to upload a module package to the App Store, yet received a very general error message.
Is the upload broken?

<img width="521" alt="image" src="https://user-images.githubusercontent.com/16342003/43569367-884c73dc-9637-11e8-9a2c-e77bc229ffa4.png">

**Comment by PoltoS** [comment]
closing as old. re-open if needed

**Comment by ralphwetzel** [comment]
@PoltoS: This still is an issue - tested today:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/16342003/50736949-d7e64c80-11c3-11e9-837f-b4a59982b52c.png">

How can I help to solve or debug this?
What kind of checks are performed - that my upload might fail due to whatever reason?
