### ISSUE TITLE
Moving one sensor element of Fibaro wall plug to another room ? does it sounds ok? 

### ISSUE THREAD

**Issue by dharam0034** [Z-Wave-Me/home-automation#490]
Hi, 

I'm working with Fibaro Wall plug and when we add the wall plug to the network and assign to a room then it shows the 4 elements as in picture. 

![1](https://user-images.githubusercontent.com/11994706/58172649-cd73ad80-7ca1-11e9-9840-409efa659dd3.PNG)

So, it can be seen that one wall plug generates 4 device elements i.e. [switch (ON/OFF), power (Watt), Energy (kwh) and not sure about the 4th, any hints about 4th element are appreciated but it is not my problem for now.)

My issue is that shouldn't all these elements should belong to the same room. Doet it make sense to not have one element in the room. For example in image below I have removed the power element.  

![2](https://user-images.githubusercontent.com/11994706/58172910-8934dd00-7ca2-11e9-8808-e90a28523335.PNG)

Lets assume that we have 10 wall plugs and therefore 40 elemets [ 10 switch (ON/OFF), 10 power (Watt), 10 Energy (kwh) and 10, the 4th element). 
 
When these wall plugs are added one by one in the a room- 

1) We can get properties (name and ID) of the all the switch devices in a room like below: 
GET: http......./v1/locations/room_ID/namespaces/devices_switchBinary
where, room_ID is 0 to N (total rooms including global room)

2) The power elements can be acquired like below: 
GET: http...v1/locations/room_ID/namespaces/devices_sensorMultilevel.meterElectric.kilowatt_hour

But, when we remove a wall plug power element from the room (like in the second image) and add it back then the order of wall plug json object is changed. The order of the switch and power elemts is not matching. 

So, does it makes sense to assign only a single element of a device to another room. Too much flexibility?
Does it make sense to measure power in some another room when the switch in is other room.

**Comment by PoltoS** [comment]
It does make sense to allow assign then to different rooms. Not forthis devices, but for double switches you can imagine that one turns the light in the kitchen, while the other in the living room - this is pretty common
