### ISSUE TITLE
Aeotec Z-Stick compatibility? And an updated docker image for Z way?

### ISSUE THREAD

**Issue by imbaimbaimba** [Z-Wave-Me/home-automation#491]
So first of all, is the Aeotec Z-stick compatible? I couldn't find a clear answer, but many seemed to say that it would not work. However in the Z-way software I get this:

>  An unexpected error occurred while initialising the Z-Wave controller data.
Please check 
1.) if the controller is plugged in correctly, 
2.) that in the app 'Z-Wave Network Access' the right port is entered 
(UZB: '/dev/ttyACM0', Box: '/dev/ttyAMA0', UZB-Windows: '\\.\COM3', Z-Stick: '/dev/ttyUSB0', embedded boxes: '/dev/ttyS0' or '/dev/ttyS1') 
3.) the app is aktiv. If not you could activate it under Menu > Apps > Activ or add a new one under Menu > Apps > Local. 
The Setting 'Expert View' needs to be active under Menu > My Settings.

I would say that seems to imply that the Z-Stick should work under /dev/ttyUSB0 .. However my Synology NAS has the Z-stick under /dev/ttyACM0, and entering that does not work.

----------------------------------

Second question, is there an updated docker image somewhere?
I used this: https://github.com/ruimarinho/docker-z-way , but it "only" gives me version 2.3.6 where as far as I can see the latest is 2.3.8 ?

**Comment by PoltoS** [comment]
Z-Way will not work with Aeotec dongle.

**Comment by PoltoS** [comment]
The docket is maintained by the community. I suppose a simple edit of https://github.com/ruimarinho/docker-z-way/blob/master/2/Dockerfile will do the job
