### ISSUE TITLE
Rasbian buster Support

### ISSUE THREAD

**Issue by miloit** [Z-Wave-Me/home-automation#493]
Hello is Buster Support already posible?

**Comment by PoltoS** [comment]
We have not yet got our RPi4 so no support yet ;( Please stay tuned

**Comment by fenst** [comment]
Sergey, Guten tag :)

When approximately can it be possible to buy RaZberry and insert it into
RPi4? Couple of weeks or couple of months?

--
С уважением, Даниил


пт, 28 июн. 2019 г. в 16:47, Poltorak Serguei <notifications@github.com>:

**Comment by PoltoS** [comment]
We are waiting to get RPi4 in hands to check it. Looks like the new Raspbian is very different.

**Comment by miloit** [comment]
And what about the Debian Buster plus the old pi3b+??

**Comment by cacherocks** [comment]
Is there any understanding when it will be possible to upgrade z-way to a version with support for the Raspbian Buster?

**Comment by PoltoS** [comment]
v3.0.2 is supporting Buster
