### ISSUE TITLE
server crash, unknown reason 

### ISSUE THREAD

**Issue by dharam0034** [Z-Wave-Me/home-automation#494]
Hi, 

I have total 81 elements in the zway netwok. Among these 47 (2 switchBinary, 1 sensorBinary,  40 sensorMultilevel, 4 switchMultilevel) are created using "HTTP Device" and 5 (sensorMultiLine) elements are created by using "Multi Sensor" app. Everything seems to be working fine for some days but then the server stops for some reason but I am not able to figure it out yet. Please help. 

logs are--

[logs190703.txt](https://github.com/Z-Wave-Me/home-automation/files/3353592/logs190703.txt)

**Comment by PoltoS** [comment]
Please help us to gather more information.

1. Please run next time in GDB:
```
cd /opt/z-way-server
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./libs:./modules gdb ./z-way-server
handle SIGPIPE nostop
handle SIGILL nostop
handle SIGHUP nostop
run
```
2. Please try to turn off some apps (ZWave, HTTPDevices) one by one and check how the system behaves - if it stops crashing, please let us know which was turned off.

3. Please monitor the memory from time to time to see if it is a memory issue

4. If you can reproduce the issue by making another installation of Z-Way (without Z-Wave shield) and reproduce the crash, please send us the backup so we can also try it (in that case we need the source of data for those HTTP devices - please provide access to URLs).

**Comment by dharam0034** [comment]
Hi, 

I tried 1 and 2. didn't help and don't know how to check memory issue. I will try 3 and 4 in some time in future since right know I have found a way around of restarting the zwayserver (when it crashed) using monit.
