### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by iamkrillin** [Z-Wave-Me/home-automation#496]
Every since the v3 upgrade, I'm not able to login to the web interface with any device.  After I enter my credentials the dashboard starts to load then the login page comes back, after which it starts to load the dashboard again, repeat until I close the tab. 

While this is occurring the message is added to the console:
Cookie 'user' possibly not set or overflowed because it was too large (17419 > 4096 bytes)!

**Comment by fenst** [comment]
Hi. I had the same issue after updating to Z-Way v3.0.0.
Cleaning all the cookies helped me

BTW, there was warning "After upgrading *clear browser cache and cookies*."
at https://z-wave.me/z-way-v3-0-0/

--
С уважением, Даниил


пн, 29 июл. 2019 г. в 15:38, iamkrillin <notifications@github.com>:

**Comment by iamkrillin** [comment]
@fenst thanks for your suggestion, I did try that and it did not help me in addition I've tried the following things:

- Clear Cookies
- Clear Cache
- Use Private Browsing
- Use another browser
- Use another device 
- Reinstall zway (using apt)

**Comment by PoltoS** [comment]
Make sure you have updated to v3.0.0 and not still on some -rcXX. This problem was fixed before this release.

You should clear cache, cookies and reload the page fully.

https://github.com/Z-Wave-Me/zwave-smarthome/commit/887af569f539470047a73694fcecea61a507264e

**Comment by iamkrillin** [comment]
apparently when I done the apt update it did not fully update my install.  I manually downloaded 3.0.0 and installed it, issue went away.  Thanks!
