### ISSUE TITLE
CHANGELOG.md stuck at 2.3.8

### ISSUE THREAD

**Issue by xrad** [Z-Wave-Me/home-automation#511]
The package is apparently now at 3.1.0 but the CHANGELOG.md only documents changes up to 2.3.8. I know there's also https://z-wave.me/ (which at least in the past was sometimes a bit hit and miss, too.) But that's more of a press release type of information. It would be nice to be able to quickly review major technical changes using the changelog (as opposed to filtering the git log.)

**Comment by PoltoS** [comment]
We are living in develop branch. Our build system takes commits from many repositories by commit ID and not by branch name, so we don't merge to master.

https://github.com/Z-Wave-Me/home-automation/blob/develop/CHANGELOG.md
