### ISSUE TITLE
Events for Scene Activation is ignored

### ISSUE THREAD

**Issue by hartmark** [Z-Wave-Me/home-automation#514]
I have several Fibaro Dimmer 2 and I have trouble of getting the scene activation to work if I press the S2-switch.

I have found this thread:
https://forum.z-wave.me/viewtopic.php?t=25984

But nothing gets shown in the "trap events.. " setting page after spamming the buttons.

![image](https://user-images.githubusercontent.com/12826053/102000903-79e60c00-3cec-11eb-8190-ce48264d0d35.png)

I see the event getting shown in the sniffer but nothing more happens from what I can see. Does anyone have any more troubleshooting hints for me?

PS. I tried to sign up for the forum at z-wave.me but I'm stuck at verify account as the email doesn't get sent.
My account name is "harre" and email "mail@hartmark.se"

**Comment by PoltoS** [comment]
This is a know issue caused by increased security in Z-Way. By the protocol Z-Way should not react on Set commans on levels other than the most secure.

In next v3.1.2 we have solved this by individually allowing unsecure or S0 secure Set commands. Please wait for the next release and there will be a fix for it by doing /JS/Run/zway.devices[NNN].data.acceptSetSecurityLevel = 80;

**Comment by hartmark** [comment]
Thanks for the quick response.
Is there any pre-release version I can try out or how can I install a developer build?

**Comment by PoltoS** [comment]
https://storage.z-wave.me/z-way-server/z-way-3.1.1-23-g786aff0_armhf.deb

**Comment by hartmark** [comment]
Thanks for the build, I didn't get any different behavour though. I see that the filename contains 3.1.1 so is this really a development build of 3.1.2?

**Comment by PoltoS** [comment]
HAve you done this?

> In next v3.1.2 we have solved this by individually allowing unsecure or S0 secure Set commands. Please wait for the next release and there will be a fix for it by doing /JS/Run/zway.devices[NNN].data.acceptSetSecurityLevel = 80;

**Comment by hartmark** [comment]
> Have you done this?
> 
> > In next v3.1.2 we have solved this by individually allowing unsecure or S0 secure Set commands. Please wait for the next release and there will be a fix for it by doing /JS/Run/zway.devices[NNN].data.acceptSetSecurityLevel = 80;

How do I do that? I'm a bit green on how the project is composed :/

**Comment by PoltoS** [comment]
Please go to page IP:8083/JS/Run/zway.devices[15].data.acceptSetSecurityLevel = 0x80 (change IP to the correct IP

**Comment by hartmark** [comment]
Cool, I got event's filled in the "Trap events from Remotes and Sensors" app and also they are created on the "Elements" page.

The only gotcha that took me a couple of minutes to realize was that the Scene ID in the event was the hex-value and the name of the element was the decimal-value. 

Perhaps a small 0x17 would have made it more clear?

Scene Activation set event:
![image](https://user-images.githubusercontent.com/12826053/102726062-e6c85a00-431b-11eb-9923-6d10a20441dd.png)

I get this element:
"Fibaro (15.0.0.23) Button"

I guess there will be a more easier accessable way to set the acceptSetSecurityLevel in the future in the expert-gui somewhere

**Comment by PoltoS** [comment]
Now acceptSetSecurityLevel as well as other configurations is available in the Expert UI under Configuration > Expert Commands
