### ISSUE TITLE
Home Assistant/Z-Way for Windows

### ISSUE THREAD

**Issue by 400HPMustang** [Z-Wave-Me/home-automation#532]
Hello, I am trying to set up the Z-Way integration in Home Assistant. I have Z-way for Windows v 3.2.1 installed on Windows 10 and running the following for Home Assistant:

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

When I enter in the server that Z-Way is installed on (10.107.112.25:8083) and the token for the homeassistant account I created in z-way I get the following message:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/45641587/172950782-d4d96b5d-7c92-4116-b7d7-984e12a7ff63.png">

**Comment by PoltoS** [comment]
Hello!

Z-Way v3.2.3 or upper is required

**Comment by 400HPMustang** [comment]
> Hello!
> 
> Z-Way v3.2.3 or upper is required

When will v3.2.3 for Windows be released?
