### ISSUE TITLE
Inovelli LZW36 Device Type

### ISSUE THREAD

**Issue by 400HPMustang** [Z-Wave-Me/home-automation#533]
I have an [Inovelli LZW36](https://inovelli.com/red-series-fan-light-switch-z-wave/) fan and light switch added to Z-way via UZB. I'm running the v3.2.1 on Windows 10. Since the device is a fan/light switch I expected to see a fan and a light. What I'm actually seeing is three dimmers. It looks like one is actually an on/off for the light, one is a dimmer for the light and the third controls the fan. 

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/45641587/173213669-67f52c68-aaf8-48dd-a245-f627b81015d9.png">

I can see in expert UI that the device type is correct

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/45641587/173213755-50803287-11dd-4f8f-b323-411340f4bd1c.png">

Is there anything that can be done to correct the way the device is displayed?

**Comment by PoltoS** [comment]
Please go in expert UI interview page, click on Interview results and then on 1. Show the content. We need to check what device type is announced there

**Comment by 400HPMustang** [comment]
There are several options for 1. Which would you like?

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/45641587/173236307-214ec3ac-b464-424d-ac4f-93e54d3e27fe.png">

**Comment by PoltoS** [comment]
All are the same.

**Comment by 400HPMustang** [comment]
> All are the same.

This is what I see when I click on "Basic"

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/45641587/173357358-d330dbd1-61e0-4643-aecb-2deafb7cd121.png">

**Comment by PoltoS** [comment]
Please click on 1 (character 1)

**Comment by 400HPMustang** [comment]
This is what I see

![image](https://user-images.githubusercontent.com/45641587/173360430-6d1bbb6b-e286-4076-ad01-ae6bf7f0a865.png)

**Comment by 400HPMustang** [comment]
When you say "change the icon" you mean the device will appear and behave as a fan and not a dimmer, correct?

**Comment by PoltoS** [comment]
actually, the dimmer and the fan differs only by icon, I believe

**Comment by PoltoS** [comment]
Looks like we don't have yet the Fan template in the integration. This is to be done

https://github.com/Z-Wave-Me/ha-core/tree/main-read-only/homeassistant/components/zwave_me
