### ISSUE TITLE
reinitialize throws error if new module

### ISSUE THREAD

**Issue by pmbert** [Z-Wave-Me/home-automation#544]
To add a new module to Z-Way I used the reinitialize:
/ZAutomation/api/v1/modules/reinitialize/MODULE

It worked fine in the past. But on 4.1.2 it throws the new error:
[2024-06-25 19:58:04.861] [I] [core] Load app "MODULE" from folder ...
[2024-06-25 19:58:04.867] [I] [core] Notification: error (dependency): Dependency not found for module: [DEP]::[MODUL] = function (a) {
        return this.filter(function(i) {return a.indexOf(i) < 0;});
    } :: MODULE

EDIT: After restarting the z-way-server, it is not reproducible.

**Comment by PoltoS** [comment]
Hi! I don't think we have ever changed this code n v4.1.2.

To add a new module please use the following API: POST /ZAutomation/api/v1/instances

For example:
```
curl 'http://localhost:8083/ZAutomation/api/v1/instances' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'ZWAYSession: 4fa273e0-de79-d133-02bf-4b519xxxxxxx' \
  --data-raw '{"moduleId":"IfThen","active":"true","title":"If -> Then","params":{"sourceDevice":{"filterIf":"switchBinary","switchBinary":{"device":"DummyDevice_24","status":"off"}},"targets":[{"filterThen":"switchBinary","switchBinary":{"target":"DummyDevice_24","status":"on","sendAction":false}}]}}' \
```
