### ISSUE TITLE
Z-Box Prepare for shutdown

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#93]
It would be useful if the Z-Box Z-Way Configuration Interface had an additional option: "Prepare for shutdown", after which users can safely remove the SD card.

edit: sorry I am afraid this is not the right place to submit this, but could not figure out where else it should go

**Comment by pz1** [comment]
With v2.0.1-RC25 I noticed there is a new "webif" with new functionality. This one did not make it (yet?) to that release

**Comment by PoltoS** [comment]
@aivs Добавьте кнопку halt в webif, пожалуйста. Полезная вешь. Желательно и Z-Way перед этим явно загасить (и подождать 10 секунд минимум).

**Comment by aivs** [comment]
Добавим.

**Comment by pz1** [comment]
It has proven to work well. Thanks
